<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 A Worked Example: Dating a Cemetery | Using Radiocarbon Dating in Archaeology</title>
  <meta name="description" content="5 A Worked Example: Dating a Cemetery | Using Radiocarbon Dating in Archaeology" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="5 A Worked Example: Dating a Cemetery | Using Radiocarbon Dating in Archaeology" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 A Worked Example: Dating a Cemetery | Using Radiocarbon Dating in Archaeology" />
  
  
  

<meta name="author" content="D. Contreras" />


<meta name="date" content="2026-03-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="radiocarbon-in-central-andean-archaeology.html"/>
<link rel="next" href="exercise-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="preparation.html"><a href="preparation.html"><i class="fa fa-check"></i><b>2</b> Preparation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="preparation.html"><a href="preparation.html#readings"><i class="fa fa-check"></i><b>2.1</b> Readings</a></li>
<li class="chapter" data-level="2.2" data-path="preparation.html"><a href="preparation.html#software"><i class="fa fa-check"></i><b>2.2</b> Software</a></li>
<li class="chapter" data-level="2.3" data-path="preparation.html"><a href="preparation.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
<li class="chapter" data-level="2.4" data-path="preparation.html"><a href="preparation.html#additional-recommended-readings"><i class="fa fa-check"></i><b>2.4</b> Additional recommended readings</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="preparation.html"><a href="preparation.html#using-radiocarbon-dating-in-archaeology"><i class="fa fa-check"></i><b>2.4.1</b> Using radiocarbon dating in archaeology</a></li>
<li class="chapter" data-level="2.4.2" data-path=""><a href="#en-espa%C3%B1ol"><i class="fa fa-check"></i><b>2.4.2</b> En español</a></li>
<li class="chapter" data-level="2.4.3" data-path="preparation.html"><a href="preparation.html#radiocarbon-dating-in-the-archaeology-of-the-central-andes"><i class="fa fa-check"></i><b>2.4.3</b> Radiocarbon dating in the archaeology of the Central Andes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="radiocarbon-dating-in-archaeology.html"><a href="radiocarbon-dating-in-archaeology.html"><i class="fa fa-check"></i><b>3</b> Radiocarbon dating in archaeology</a></li>
<li class="chapter" data-level="4" data-path="radiocarbon-in-central-andean-archaeology.html"><a href="radiocarbon-in-central-andean-archaeology.html"><i class="fa fa-check"></i><b>4</b> Radiocarbon in Central Andean archaeology</a></li>
<li class="chapter" data-level="5" data-path="cemetery.html"><a href="cemetery.html"><i class="fa fa-check"></i><b>5</b> A Worked Example: Dating a Cemetery</a>
<ul>
<li class="chapter" data-level="5.1" data-path="cemetery.html"><a href="cemetery.html#working-with-simulated-radiocarbon-data"><i class="fa fa-check"></i><b>5.1</b> Working with simulated (radiocarbon) data</a></li>
<li class="chapter" data-level="5.2" data-path="cemetery.html"><a href="cemetery.html#distribution-of-events-in-time"><i class="fa fa-check"></i><b>5.2</b> <em>Distribution</em> of events in time</a></li>
<li class="chapter" data-level="5.3" data-path="cemetery.html"><a href="cemetery.html#archaeological-approaches-to-a-cemetery-population"><i class="fa fa-check"></i><b>5.3</b> Archaeological approaches to a cemetery population</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="cemetery.html"><a href="cemetery.html#estimating-the-age-of-burials"><i class="fa fa-check"></i><b>5.3.1</b> Estimating the age of burials</a></li>
<li class="chapter" data-level="5.3.2" data-path="cemetery.html"><a href="cemetery.html#sampling-and-precision"><i class="fa fa-check"></i><b>5.3.2</b> Sampling and precision</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="cemetery.html"><a href="cemetery.html#approaching-a-cemetery-population-using-radiocarbon"><i class="fa fa-check"></i><b>5.4</b> Approaching a cemetery population using radiocarbon</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="cemetery.html"><a href="cemetery.html#what-canshould-we-date"><i class="fa fa-check"></i><b>5.4.1</b> What can/should we date?</a></li>
<li class="chapter" data-level="5.4.2" data-path="cemetery.html"><a href="cemetery.html#what-happens-when-we-submit-one-of-those-samples-to-a-radiocarbon-laboratory"><i class="fa fa-check"></i><b>5.4.2</b> What happens when we submit one of those samples to a radiocarbon laboratory?</a></li>
<li class="chapter" data-level="5.4.3" data-path="cemetery.html"><a href="cemetery.html#calibrating-a-date-in-oxcal"><i class="fa fa-check"></i><b>5.4.3</b> Calibrating a date in OxCal</a></li>
<li class="chapter" data-level="5.4.4" data-path="cemetery.html"><a href="cemetery.html#curves"><i class="fa fa-check"></i><b>5.4.4</b> Calibration curves</a></li>
<li class="chapter" data-level="5.4.5" data-path="cemetery.html"><a href="cemetery.html#oxcal-code"><i class="fa fa-check"></i><b>5.4.5</b> OxCal code</a></li>
<li class="chapter" data-level="5.4.6" data-path="cemetery.html"><a href="cemetery.html#introducing-real-world-complications"><i class="fa fa-check"></i><b>5.4.6</b> Introducing real-world complications</a></li>
<li class="chapter" data-level="5.4.7" data-path="cemetery.html"><a href="cemetery.html#managing-real-world-complications-through-modeling"><i class="fa fa-check"></i><b>5.4.7</b> Managing real-world complications through modeling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="exercise-1.html"><a href="exercise-1.html"><i class="fa fa-check"></i><b>6</b> Exercise 1</a></li>
<li class="chapter" data-level="7" data-path="exercise-2.html"><a href="exercise-2.html"><i class="fa fa-check"></i><b>7</b> Exercise 2</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using Radiocarbon Dating in Archaeology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cemetery" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> A Worked Example: Dating a Cemetery<a href="cemetery.html#cemetery" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>A common challenge in archaeology is the excavated cemetery.</p>
<p><img src="imgs/Prieto2019_Fig3.png" /></p>
<p>While in some ways cemeteries are unique - embodying uniquely simplified depositional processes, compared to domestic sites - in other ways they present some challenges common to many archaeological context. One of the most salient of those challenges is distribution in time. We might want to know (among other things):</p>
<ul>
<li>When did use as a cemetery begin?</li>
<li>For how long was the area used as a cemetery?</li>
<li>When did use as a cemetery end?</li>
<li>Was there a period of more intense use, and if so when and for how long?</li>
</ul>
<p>In the case of a cemetery the events are interments - but the same logic applies to construction, habitation, use of ceramics, etc.</p>
<div id="working-with-simulated-radiocarbon-data" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Working with simulated (radiocarbon) data<a href="cemetery.html#working-with-simulated-radiocarbon-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll work here mostly with simulated data, rather than real archaeological data. Why? So that we can evaluate our results against a <em>known</em> ‘reality’. In Exercise 1 we will posit a given pattern of activity that produced a burial population (<em>e.g.</em>, regular burial over 200 years, or a slow start followed by a century of peak activity followed by a slow decline, etc.), generate some simulated radiocarbon data from that burial population (<em>i.e.</em>, sample that population randomly, then simulate radiocarbon dates from those samples), then calibrate the dates and examine our results to see how closely we can reproduce the original distribution. Then - Exercise 2 - we will introduce some complications that reflect the messy reality of our radiocarbon samples, which for a variety of reasons that we’ll consider may not exactly reflect the dates that we want to know. Keep in mind throughout that there are two levels of stochastic effects here: both our selection of calendar dates and the radiocarbon dates that we simulate from those are random, and we would get slightly different results if we were to carry out the process again.</p>
</div>
<div id="distribution-of-events-in-time" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> <em>Distribution</em> of events in time<a href="cemetery.html#distribution-of-events-in-time" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Basic inferences about a cemetery are fundamentally problems of sampling and distribution:</p>
<ul>
<li>Uniform (<em>x</em> burials/year for <em>y</em> years)</li>
<li>Normal - Single event (sacrifice,plague, etc - unlikely but not unimaginable)</li>
<li>Exponential (frequency of use increasing over time)</li>
<li>Negative exponential (frequency of use decreasing over time)</li>
<li><em>actual</em> distribution can be represented precisely by a pdf</li>
</ul>
<p><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-3-1.png" width="672" /><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-3-2.png" width="672" /><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-3-3.png" width="672" /><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-3-4.png" width="672" /></p>
</div>
<div id="archaeological-approaches-to-a-cemetery-population" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Archaeological approaches to a cemetery population<a href="cemetery.html#archaeological-approaches-to-a-cemetery-population" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We might have something like this: <img src="imgs/HCV_cementerioLambayeque.jpeg" /></p>
<p>…and we might want to know (among other things):</p>
<ul>
<li>When did use as a cemetery begin?</li>
<li>For how long was the area used as a cemetery?</li>
<li>When did use as a cemetery end?</li>
<li>Was there a period of more intense use, and if so when and for how long?</li>
</ul>
<p>These are fundamentally problems of <em>age estimation</em> and <em>sampling</em>.</p>
<p>Likelihood of the age of a given sample is governed by this distribution.</p>
<p>With <em>enough</em> sample ages, can reconstruct distribution. <em>How many</em> is <em>enough</em> depends on the distribution and on how confident we want to be.</p>
<p>So…how do we estimate the ages of burials? What precision do we need?</p>
<div id="estimating-the-age-of-burials" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Estimating the age of burials<a href="cemetery.html#estimating-the-age-of-burials" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Radiocarbon is of course not the only tool available for estimating the age of burials. More commonly - because cheaper and easier - we might use diagnostic material culture</p>
<p>Non-14c tools: typology, tpq and taq, dendro ( this isn’t an intro-to-arch class, so mostly we don’t need to catalog these…except to note that they’re probably going to be unsatisfying in terms of precision and reliability, and that they may be interesting sources of <em>priors</em>)</p>
</div>
<div id="sampling-and-precision" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Sampling and precision<a href="cemetery.html#sampling-and-precision" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our age estimates need to achieve some level of precision in order to be useful. That level depends on questions of interest. If all we care about is that cemetery use occurred between <em>x</em> and <em>y</em>, and we’re not worried about whether use actually <em>fillled</em> that span, then little precision and few samples are required. That is, if we can estimate the ages of a handful of burials, using whatever method, we can say with reasonable confidence that the cemetery was in use between <em>a</em> and <em>b</em>.</p>
<p>For example, let’s suppose that our cemetery was in use between 800 - 1100 CE, and that every year within that span, 5 individuals were interred. This would give us a burial population of 1500 individuals, uniformly distributed throughout that span. Let’s further suppose that each of these individuals conveniently has their date of death - in some format that we can decipher - inscribed on a sherd buried with them. Using that, we catalog the ages of five burials.</p>
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
ages
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1074
</td>
</tr>
<tr>
<td style="text-align:right;">
1081
</td>
</tr>
<tr>
<td style="text-align:right;">
886
</td>
</tr>
<tr>
<td style="text-align:right;">
1049
</td>
</tr>
<tr>
<td style="text-align:right;">
993
</td>
</tr>
</tbody>
</table>
<p>Can we now answer our questions about the cemetery? i.e., when it was first used, and when it fell out of use? In fact, even with the ability to very precisely date burials, our best estimate of the span of use of the cemetery is 886 - 1081 CE - we are limited by our small sample.</p>
<p>What if we take a sample four times bigger, of 20 individuals? A list that long starts to get difficult to work with, so we’ll plot them instead, including our original 5 in red.</p>
<table class=" lightable-minimal" style="font-size: 7px; font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:right;">
ages
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1074
</td>
</tr>
<tr>
<td style="text-align:right;">
1081
</td>
</tr>
<tr>
<td style="text-align:right;">
886
</td>
</tr>
<tr>
<td style="text-align:right;">
1049
</td>
</tr>
<tr>
<td style="text-align:right;">
993
</td>
</tr>
<tr>
<td style="text-align:right;">
956
</td>
</tr>
<tr>
<td style="text-align:right;">
1021
</td>
</tr>
<tr>
<td style="text-align:right;">
840
</td>
</tr>
<tr>
<td style="text-align:right;">
997
</td>
</tr>
<tr>
<td style="text-align:right;">
1012
</td>
</tr>
<tr>
<td style="text-align:right;">
937
</td>
</tr>
<tr>
<td style="text-align:right;">
1016
</td>
</tr>
<tr>
<td style="text-align:right;">
1080
</td>
</tr>
<tr>
<td style="text-align:right;">
877
</td>
</tr>
<tr>
<td style="text-align:right;">
939
</td>
</tr>
<tr>
<td style="text-align:right;">
1082
</td>
</tr>
<tr>
<td style="text-align:right;">
1093
</td>
</tr>
<tr>
<td style="text-align:right;">
835
</td>
</tr>
<tr>
<td style="text-align:right;">
942
</td>
</tr>
<tr>
<td style="text-align:right;">
968
</td>
</tr>
</tbody>
</table>
<p><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Our estimate now would be that use of the cemetery began in 835 CE and lasted until 1093 CE. We’re having trouble capturing the actual beginning and ending just because the odds are only 5:1500 that we’ll get a burial from any given year.</p>
<p>Of course, it’s wildly unlikely that we’ll be able to estimate the age of each burial with annual precision. Does it matter? What if we take those same 20 individuals, and instead make the (still optimistic) assumption that we have a reliable high-precision ceramic sequence, which we can use to estimate the age of any burial within phases of 40 years.</p>
<table class=" lightable-minimal" style="font-size: 7px; font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:right;">
ages
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1080
</td>
</tr>
<tr>
<td style="text-align:right;">
1120
</td>
</tr>
<tr>
<td style="text-align:right;">
920
</td>
</tr>
<tr>
<td style="text-align:right;">
1080
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
960
</td>
</tr>
<tr>
<td style="text-align:right;">
1040
</td>
</tr>
<tr>
<td style="text-align:right;">
840
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1040
</td>
</tr>
<tr>
<td style="text-align:right;">
960
</td>
</tr>
<tr>
<td style="text-align:right;">
1040
</td>
</tr>
<tr>
<td style="text-align:right;">
1080
</td>
</tr>
<tr>
<td style="text-align:right;">
880
</td>
</tr>
<tr>
<td style="text-align:right;">
960
</td>
</tr>
<tr>
<td style="text-align:right;">
1120
</td>
</tr>
<tr>
<td style="text-align:right;">
1120
</td>
</tr>
<tr>
<td style="text-align:right;">
840
</td>
</tr>
<tr>
<td style="text-align:right;">
960
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-6-1.png" alt="Sampling from burials uniformly distributed between 800 - 1100 CE. Burial years in black/red; estimated to nearest 40 years in grey." width="672" />
<p class="caption">
Figure 5.1: Sampling from burials uniformly distributed between 800 - 1100 CE. Burial years in black/red; estimated to nearest 40 years in grey.
</p>
</div>
<p>Now we might suggest that cemetery use began around 840 and ended by about 1120. We might even think about suggesting - wrongly, it turns out - that use increased over time. And what might our interpretion be if we had only those original five individuals to work with?</p>
<p>Of course, 40 years would be remarkably high precision for ceramic phases, and if we had that, we might not be too interested in radiocarbon. What happens if we think more realistically (for many archaeological scenarios) about ceramics that can be identified to within 100 or 200 years?</p>
<table class=" lightable-minimal" style="font-size: 7px; font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:right;">
ages
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1200
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
<tr>
<td style="text-align:right;">
1000
</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-7-1.png" alt="Sampling from burials uniformly distributed between 800 - 1100 CE. Burial years in black/red; estimated to nearest 200 years in grey." width="672" />
<p class="caption">
Figure 5.2: Sampling from burials uniformly distributed between 800 - 1100 CE. Burial years in black/red; estimated to nearest 200 years in grey.
</p>
</div>
<p>Here we would likely produce some interestingly wrong interpretations. The low precision with which we can date burials would suggest to us that cemetery use began as early as 700 CE, while that low precision combines with sampling effects to lead us to suggest an increase in use over time, ending at 1100 CE (a date which we might <em>also</em> have gotten wrong, had our ceramic chronology not happened to have a phase that ended then).</p>
<p>We could carry on, varying sample size and precision, and exploring how well we felt able to describe cemetery use. Since our goal here is to be thinking about radiocarbon, we won’t pursue that, but let’s take a quick look at what happens if we consider a different model of cemetery use. What if, rather than 5 individuals/year for 300 years, cemetery use started slowly, peaked in 950, and then slowly declined?</p>
<table class=" lightable-minimal" style="font-size: 7px; font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:right;">
ages
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1019
</td>
</tr>
<tr>
<td style="text-align:right;">
922
</td>
</tr>
<tr>
<td style="text-align:right;">
968
</td>
</tr>
<tr>
<td style="text-align:right;">
982
</td>
</tr>
<tr>
<td style="text-align:right;">
970
</td>
</tr>
<tr>
<td style="text-align:right;">
945
</td>
</tr>
<tr>
<td style="text-align:right;">
1026
</td>
</tr>
<tr>
<td style="text-align:right;">
945
</td>
</tr>
<tr>
<td style="text-align:right;">
1051
</td>
</tr>
<tr>
<td style="text-align:right;">
947
</td>
</tr>
<tr>
<td style="text-align:right;">
1015
</td>
</tr>
<tr>
<td style="text-align:right;">
1064
</td>
</tr>
<tr>
<td style="text-align:right;">
881
</td>
</tr>
<tr>
<td style="text-align:right;">
936
</td>
</tr>
<tr>
<td style="text-align:right;">
943
</td>
</tr>
<tr>
<td style="text-align:right;">
982
</td>
</tr>
<tr>
<td style="text-align:right;">
936
</td>
</tr>
<tr>
<td style="text-align:right;">
817
</td>
</tr>
<tr>
<td style="text-align:right;">
828
</td>
</tr>
<tr>
<td style="text-align:right;">
1016
</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-8-1.png" alt="Sampling from burials normally distributed between 800 - 1100 CE. Burial years in black; estimated to nearest 40 years in grey." width="672" />
<p class="caption">
Figure 5.3: Sampling from burials normally distributed between 800 - 1100 CE. Burial years in black; estimated to nearest 40 years in grey.
</p>
</div>
<p>Here we might suggest that cemetery use began around 840 and ended by about 1080. We can also detect a pattern of increased use ca. 950 - 1000 CE.</p>
<p>We might achieve something similar, if the span identified in regional chronological schemes with Lambayeque material culture were 800 - 1100 CE, simply by sampling a <em>single burial</em> and identifying some diagnostic piece of material culture. But what if ceramic/cultural chronology is insufficiently precise…or inaccurate? What if the span identified in regional chronological schemes with Lambayeque material culture were 700 - 1200 CE, rather than 800 - 1100 CE…or 950 - 1200 CE? We would be badly wrong, and in a way that mattered for our interpretation of both the site and for regional patterns.</p>
<p>Keep in mind as we address radiocarbon dating that we are focusing on the accuracy and precision with which we can estimate ages. As we’ve just seen, though, all the accuracy and precision in the world won’t (and can’t) address the uncertainties created by small samples.</p>
<p>Keep in mind also that these dated events - burials, in the case of our cemetery - could as easily be house abandonments, or offerings, or discard of recognizable (diagnostic) ceramics.</p>
</div>
</div>
<div id="approaching-a-cemetery-population-using-radiocarbon" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Approaching a cemetery population using radiocarbon<a href="cemetery.html#approaching-a-cemetery-population-using-radiocarbon" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Radiocarbon promises to solve some of these problems for us; under ideal circumstances we might be able to produce age estimates for date-of-interment accurate within 20-30 years for each individual. Supposing that we do settle on radiocarbon as a useful method that might offer us a solution to the imprecision of our ceramic chronology. What <em>can</em> we date, what <em>should</em> we date, and what <em>can we do</em> with the results? If we produce 20 radiocarbon age estimates on 20 interments with which to approach our questions about cemetery use - what does <em>their</em> distribution look like? To assess that distribution, we need to understand those radiocarbon age estimates. We’ll take a quick look here at how we get from measured carbon isotope ratio to radiocarbon age to calendar age, and then focus on what you, as a practicing archaeologist, might receive from a lab to which you’ve submitted samples. We’ll begin simply, and then introduce several issues that might complicate our interpretation of radiocarbon ages.</p>
<div id="what-canshould-we-date" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> What can/should we date?<a href="cemetery.html#what-canshould-we-date" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s consider a single interment, examining the potentially dateable material available.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="imgs/brujo_entierro11.png" alt="Entierro 11/92, Huaca Cao Viejo (Complejo Arqueológico El Brujo archives)." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.4: Entierro 11/92, Huaca Cao Viejo (Complejo Arqueológico El Brujo archives).
</p>
</div>
<p>There are two guiding questions here.</p>
<details>
<summary>
<b>1. What is the event whose age we wish to know (the <em>target event</em>)?</b>
</summary>
<p>The answer (usually) is the depositional event - the moment of burial. Clarity about this is important because we might also for various reasons be interested in the moment of death, a moment of manufacture of some included material culture, a moment of disturbance of the burial, etc. With respect to our overarching questions about the cemetery, however, it’s most likely that what we want is the date of interment, which then is our <em>target event</em>.</p>
</details>
<details>
<summary>
<b>2. For which materials from this context might we be able to estimate an age using radiocarbon?</b>
</summary>
<p>We are fortunate in that there are multiple dateable materials in this context (a luxury!).</p>
<ul>
<li>ceramics may contain organic material (remnants of temper) and/or absorbed organic residues (1/5)</li>
<li>gourd (<em>Lagenaria siceraria</em>) (3)</li>
<li>textile fragment (6)</li>
<li>wood (algarrobo, <em>Prosopis pallida</em>) (2)</li>
<li>marine shell (4)</li>
<li>human bone (9)</li>
<li>camelid bone (8)</li>
<li>caña brava (<em>Gynerium sagittatum</em>) (7)</li>
<li>charcoal is not visible in the sketch, but because it’s such a commonly dated material let’s assume that some unidentified wood charcoal is present</li>
</ul>
</details>
<p>Identifying these materials as potentially dateable, and clearly understanding what results they’re likely to produce, takes us back to the fundamentals of <span class="math inline">\(^{14}C\)</span> as a dating method. Bayliss and Marshall <span class="citation">(2022, sec. 3.2)</span> cover the logic and pitfalls of sample selection in greater detail than we can here.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="imgs/velarde_moche14C.png" alt="The carbon cycle." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.5: The carbon cycle.
</p>
</div>
<p>The key points - you can review the method in detail elsewhere; see <a href="preparation.html#readings">above</a> - are:</p>
<ul>
<li>atmospheric <span class="math inline">\(^{14}C\)</span> - an unstable isotope of carbon that will radioactively decay - is produced by cosmic ray bombardment</li>
<li><span class="math inline">\(^{14}C\)</span> - like other isotopes of <span class="math inline">\(C\)</span>, <span class="math inline">\(^{12}C\)</span> and <span class="math inline">\(^{13}C\)</span> - oxidizes to form <span class="math inline">\(CO_{2}\)</span></li>
<li>that <span class="math inline">\(CO_{2}\)</span> disperses through the atmosphere, and then enters terrestrial and marine food chains when photosynthesized by plants</li>
<li>the carbon that plants and animals use to build tissue is derived from consumption of those plants - or of animals that consume those plants</li>
</ul>
<p>Because this process is relatively rapid and because the atmosphere mixes, the ratio of carbon isotopes (<em>e.g.</em>, <span class="math inline">\(^{14}C:^{13}C\)</span>) in plant and animal tissue is in equilibrium with the ratio in the atmosphere at any given time. That is, in the illustration above, the proportion of the carbon that is <span class="math inline">\(^{14}C\)</span> is the same in the atmosphere, the grass that photosynthesizes atmospheric <span class="math inline">\(CO_{2}\)</span>, the camelid that eats the grass, and the human hunter that eats the camelid.</p>
<p>When an organism dies, it ceases to incorporate carbon into its tissue, and the <span class="math inline">\(^{14}C\)</span> incorporated into tissue while it was alive begins to radioactively decay. As a result, the proportion of <span class="math inline">\(^{14}C\)</span> in that organism begins to decrease. Because that rate of decay is known, is unaffected by environmental factors, and has not changed over time - the half-life of <span class="math inline">\(^{14}C\)</span> is 5730±40 years - the ratio of remaining <span class="math inline">\(^{14}C\)</span> to <span class="math inline">\(^{13}C\)</span> can be measured and used to estimate the amount of time that has passed since the organism stopped incorporating carbon. It’s that measurement that a radiocarbon lab reports to the consumer, adjusted by convention to a BP timescale (‘before present’, where ‘present’ is fixed at 1950 CE).</p>
</div>
<div id="what-happens-when-we-submit-one-of-those-samples-to-a-radiocarbon-laboratory" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> What happens when we submit one of those samples to a radiocarbon laboratory?<a href="cemetery.html#what-happens-when-we-submit-one-of-those-samples-to-a-radiocarbon-laboratory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Laboratory procedures are intended to achieve two goals: 1) to make sure that the sample being measured consists exclusively of the material whose age is of interest, and 2) to accurately and precisely measure the radiocarbon age of the sample. What happens after that - how that radiocarbon age relates to the <em>target event</em>, and what that means for your questions - is your problem.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="imgs/AMS_process.png" alt="Sample processing in AMS radiocarbon analysis." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.6: Sample processing in AMS radiocarbon analysis.
</p>
</div>
<p>Pretreatment <span class="citation">(see Wood 2015, 63–65)</span> is the process in which chemical and physical means are used to remove potential contaminants from the sample. Contaminants, even small amounts of which can significantly affect age estimates (see Blaauw’s ‘Contaminate-a-date’ app, found on his webpage [<a href="https://maarten14c.github.io/" class="uri">https://maarten14c.github.io/</a>] under <code>Software and animations</code> / <code>impact of contamination on C-14 ages</code>) - are materials other than the sample, which might introduce carbon of different age. This can range from manual removal of macroscopic rootlets from charcoal to microscopic inspection to acid and base washes. Following pretreatment samples are combusted, converted into graphite and pressed into pellets that be analyzed in the atomic mass spectrometer, in which the carbon isotopes are separated by weight and counted. The measured ratio that results forms the basis of the calculated radiocarbon age that the lab reports. That radiocarbon age will look something like this example: <strong>LabID-XXX | 1100 ±40</strong>.</p>
<p>The three components here are not the only things that matter, but they are the fundamental ingredients without which the date is not useful: the unique laboratory identifier, the radiocarbon age, and the estimated error (reported by convention as 1<span class="math inline">\(\sigma\)</span>). That error represents the uncertainty with which the lab calculates the radiocarbon age, which is to say that the actual value is most likely to be 1100, is very probably close to that value, but might be as low as 1020 or as high as 1180, if we account for ~95% of the probability distribution).</p>
<p>That measured age looks like this, if we plot it as a probability curve.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-12-1.png" alt="2-sigma distribution of 1100 ±40." width="672" />
<p class="caption">
Figure 5.7: 2-sigma distribution of 1100 ±40.
</p>
</div>
<p>This is quite a manageable amount of uncertainty, and it’s not hard to imagine that if we had 20 values like this, we could plot them on a timeline, producing something not unlike the plots that we were looking at above (where the uncertainty around each age is uniformly distributed, which is to say that if we know that an age falls in the 1020 - 1060 CE bin, it’s equally likely to be any of the ages in that bin). <em>However</em>, because atmospheric production of <span class="math inline">\(^{14}C\)</span> has fluctuated over time - varying depending on cosmic radiation, sometimes in <a href="https://en.wikipedia.org/wiki/Miyake_event">dramatic ways</a> that have some neat implications for archaeological dating <span class="citation">(Price 2023; Dee and Pope 2016)</span> - the same calculated radiocarbon age might have been produced by a sample originating in multiple different calendar years. Thanks to the efforts of the international community of radiocarbon researchers, this problem can be managed, because we can describe fairly precisely exactly how atmospheric radiocarbon has varied over the last 14000 years. These descriptions - slightly different for the northern and southern hemisphere because atmospheric mixing is in fact neither complete nor instantaneous (see <span class="citation">(Hua et al. 2022)</span>) - are the <em>calibration curves</em> that are periodically updated by the community: the current versions are IntCal20 <span class="citation">(Reimer et al. 2020)</span> and SHCal20 <span class="citation">(Hogg et al. 2020)</span>. These curves are measures - compiled by radiocarbon-dating many known-age tree ring samples at multiple labs - of changing atmospheric radiocarbon over time (to explore the underpinnings of IntCal20, see Maarten Blaauw’s <a href="https://radiocarbon.shinyapps.io/calibrationcurve/">Shiny app</a>).</p>
<p>When we <em>calibrate</em> a radiocarbon date, we are asking, “In what calendar year(s) might the amount of 14C that we’ve measured been produced?” The answer depends on the calibration curve. The result is an irregular curve (a <em>probability density function</em> [pdf]) that describes the range of calendar dates that might have produced our conventional radiocarbon age. Because the calibration curve is not smooth, this probability is not evenly distributed (unlike, for example, the symmetrical uncertainty described by the ‘±’ in the conventional radiocarbon age). This pdf is usually summarized by referencing the 95% <em>high-density region</em> (HDR), which describes the highest parts of pdf, summing them until 95% (or whatever desired range) of the area under the curve is captured. Because of the irregularity of the pdf, these may not be contiguous.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-13-1.png" alt="Calibrated age of LabID-XXX (1100 ±40). Calibrated using the R package **rice** (Blaauw 2024)." width="672" />
<p class="caption">
Figure 5.8: Calibrated age of LabID-XXX (1100 ±40). Calibrated using the R package <strong>rice</strong> (Blaauw 2024).
</p>
</div>
<p>On the y-axis we can see our conventional radiocarbon age, plotted as the normal distribution described by that value and the associated error that the lab reports (reflecting measurement uncertainty). In green is the calibration curve - in this case IntCal20 - and on the x-axis is the <em>probability density function</em> that describes the span of time during which our sample might have been produced (over which, notably, it’s more likely to have been produced in some years than in others). The HDR is shaded, and described in the upper right corner (most of the likelihood - 93.1% of the upper 95% - falls in the span 878 - 1024 CE, but there’s a 1.4% chance that our sample was produced between 776 and 783 CE).</p>
<p>Maarten Blaauw has produced this animated visualization to illustrate how we get from the conventional radiocarbon age to calibrated pdf:</p>
<video width="640" height="480" controls>
<source src="imgs/calibrate_fast.webm" type="video/webm">
</video>
<p>When you calibrate a date in OxCal you’ll get something similar, or you can produce plots exactly like this in <em>R</em> using the <strong>rice</strong> package, or using Maarten Blaauw’s <a href="https://radiocarbon.shinyapps.io/calibrate/">Shiny app for calibration</a>.</p>
</div>
<div id="calibrating-a-date-in-oxcal" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Calibrating a date in OxCal<a href="cemetery.html#calibrating-a-date-in-oxcal" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To calibrate a single date in OxCal, launch the browser-based program [<a href="https://c14.arch.ox.ac.uk/oxcal/OxCal.html" class="uri">https://c14.arch.ox.ac.uk/oxcal/OxCal.html</a>], and log in when prompted. Click either of the ‘Calibrate’ buttons, and fill in the name of the sample (usually the lab ID, though you may sometimes find it convenient to use other names), the conventional radiocarbon age, and the measurement error (see below).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="imgs/oxcal/calibrate.png" alt="Calibrating a single date in OxCal." width="60%" style="float:left; padding:10px" />
<p class="caption">
Figure 5.9: Calibrating a single date in OxCal.
</p>
</div>
<p>This will produce a plot similar to the one above, which illustrates the radiocarbon determination on the y-axis, the calibration curve, and, on the x-axis, the calibrated date that results from the intersection of those two. The HDR is also marked (by the brackets under the pdf) and enumerated at the upper right. The styling of this plot can be adjusted using the ‘Edit’–&gt;‘Format’ drop-down menu.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="imgs/oxcal/calibrated_result.png" alt="Calibrated result from OxCal." width="60%" style="padding:10px" /><img src="imgs/oxcal/plot_format.png" alt="Calibrated result from OxCal." width="40%" style="padding:10px" />
<p class="caption">
Figure 5.10: Calibrated result from OxCal.
</p>
</div>
</div>
<div id="curves" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Calibration curves<a href="cemetery.html#curves" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As noted above, calibration is necessary because atmospheric radiocarbon has varied over time. It also varies in space (Fig. 5.11), driven at global scales by the contrast in relative land area in the northern and southern hemispheres and the relative segregation of the air masses in those hemispheres <span class="citation">(see Erik J. Marsh et al. 2018, 926–27 for an overview)</span>. Two distinct calibration curves are the result: IntCal for the northern hemisphere and SHCal for the southern; current versions, published in 2020, are IntCal20 <span class="citation">(Reimer et al. 2020)</span> and SHCal20 <span class="citation">(Hogg et al. 2020)</span>. These are only modestly different (Figure 5.12), but that slight difference can affect where the radiocarbon determination intersects the calibration curve (see Fig. 5.13, where the bulk of the probability shifts only slightly, but the tail moves from pre-900 CE to post-1050 CE).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="imgs/Hua2022_Fig1.png" alt="Hua and colleagues (2022) illustrate 20th-21st century  variability in atmospheric radiocarbon, based on atmospheric CO2 sampling (triangles) and Δ14C tree-ring records (circles)." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.11: Hua and colleagues (2022) illustrate 20th-21st century variability in atmospheric radiocarbon, based on atmospheric CO2 sampling (triangles) and Δ14C tree-ring records (circles).
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-17-1.png" alt="IntCal20 and SHCal20 from 1000 BCE to 1000 CE. Plotted using the R package **rice** (Blaauw 2024)." width="672" />
<p class="caption">
Figure 5.12: IntCal20 and SHCal20 from 1000 BCE to 1000 CE. Plotted using the R package <strong>rice</strong> (Blaauw 2024).
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-18"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-18-1.png" alt="Calibrated age of LabID-XXX (1100 ±40). Calibrated using the R package **rice** (Blaauw 2024)." width="50%" /><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-18-2.png" alt="Calibrated age of LabID-XXX (1100 ±40). Calibrated using the R package **rice** (Blaauw 2024)." width="50%" />
<p class="caption">
Figure 5.13: Calibrated age of LabID-XXX (1100 ±40). Calibrated using the R package <strong>rice</strong> (Blaauw 2024).
</p>
</div>
<div id="specifying-a-calibration-curve-in-oxcal" class="section level4 hasAnchor" number="5.4.4.1">
<h4><span class="header-section-number">5.4.4.1</span> Specifying a calibration curve in OxCal<a href="cemetery.html#specifying-a-calibration-curve-in-oxcal" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You can select calibration curves in OxCal by clicking on ‘Options’ and then ‘Calibration’ (Fig. 5.14).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="imgs/oxcal/curve_selection.png" alt="Calibration curve selection in OxCal." width="60%" style="float:right; padding:10px" />
<p class="caption">
Figure 5.14: Calibration curve selection in OxCal.
</p>
</div>
<p>To juxtapose two versions of the same date calibrated with different curves in OxCal, we need a more complicated interface than what we use to calibrate a singe date, because we need to enter more information than just a radiocarbon determination and associated error. To open such an interface, select ‘File’–&gt;‘New’.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-20"></span>
<img src="imgs/oxcal/new_project.png" alt="Opening a new project in OxCal." width="60%" style="float:left; padding:10px" />
<p class="caption">
Figure 5.15: Opening a new project in OxCal.
</p>
</div>
<p>By default the ‘Input’ window that opens shows the ‘Model’ view. You can (and should) change this using the buttons at the lower left (Figure 5.16). The ‘List’ view shows you the structure of your model - we’re building models now! - and the ‘Code’ view shows you what’s under the hood. Toggling back and forth between those is a good way to get familiar with the actual code. In your new ‘Input’ window, select the dot below and indented from <code>Plot()</code>, and then click on ‘Insert’, and, in the pop-up that appears, <code>R_Date</code>. This will pop up a familiar interface for entering a radiocarbon date (Figure 5.17). Once you’ve entered that date, click ‘Insert’, and it will appear in the ‘Input’ window. Do this twice, changing the name (<em>e.g.</em>, “LabID-XXX.1” and “LabID-XXX.2”) so that you can tell the two dates apart. Before we run this model, we need to specify that we want to use a different calibration curve for each date. Select the first date by clicking on it in the ‘Input’ window (it will turn <span style="color: blue;">blue</span>), and select ‘Tools’ –&gt; ‘Curves’, then ‘Atmospheric’, and finally ‘IntCal20’ (Figure 5.18). A new line will appear above your date, which reads <code>Curve("IntCal20","intcal20.14c")</code>. Now highlight the second date and repeat the process, but selecting ‘SHCal20’. You should now have four lines in your model (inside the ‘Plot’ command). OxCal reads from top to bottom, so that when you run the code, it will apply the last curve it’s found to the next date it encounters.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="imgs/oxcal/input_window.png" alt="Changing views in the OxCal 'Input' window." width="60%" style="float:right; padding:10px" />
<p class="caption">
Figure 5.16: Changing views in the OxCal ‘Input’ window.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-22"></span>
<img src="imgs/oxcal/insert_dates.png" alt="Inserting dates in the OxCal 'Input' window." width="60%" style="float:right; padding:10px" />
<p class="caption">
Figure 5.17: Inserting dates in the OxCal ‘Input’ window.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-23"></span>
<img src="imgs/oxcal/input_curves.png" alt="Inputting curves into an OxCal model." width="60%" style="float:right; padding:10px" />
<p class="caption">
Figure 5.18: Inputting curves into an OxCal model.
</p>
</div>
<p>The ‘Run’ button at the upper right of the ‘Input’ window (or selecting ‘File’–&gt;‘Run’ from the dropdown) will run your model - which is to say, in this case, calibrate the two radiocarbon dates you’ve entered, using the two different curves that you’ve specified. The results will appear in a new window (‘Table’). Select ‘View’–&gt;‘Plot dates’ to see these results and ‘View’–&gt;‘Plot stacks’ to overlay them. Plots will appear in a new ‘OxCal plot’ window, where results can be manipulated using the ‘Edit’ dropdown and downloaded (as .pdf, .png, or .svg image files) with ‘File’–&gt;‘Save as’.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-24"></span>
<img src="imgs/oxcal/curves_results.png" alt="Plotting results." width="50%" style="padding:10px" /><img src="imgs/oxcal/curves_results_stack.png" alt="Plotting results." width="50%" style="padding:10px" />
<p class="caption">
Figure 5.19: Plotting results.
</p>
</div>
</div>
<div id="calibration-at-low-latitudes" class="section level4 hasAnchor" number="5.4.4.2">
<h4><span class="header-section-number">5.4.4.2</span> Calibration at low latitudes<a href="cemetery.html#calibration-at-low-latitudes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As Figure 5.11 implies, it’s not always obvious which calibration curve is appropriate, particularly at tropical latitudes. Atmospheric circulation patterns also vary seasonally: note that Fig. 5.11 illustrates two different - December–February [DJF] and June–August [JJA] locations for the tropical low pressure band [TLPB], which Hua and colleagues prefer to the inter-tropical convergence zone [ITCZ] because it can be more precisely described in terrestrial areas. This is of particular importance for South American archaeology (Fig. 5.19); note how far south the TLPB moves during the austral summer. Atmospheric circulation patterns have also varied over time, since the location of the ITCZ is closely linked to climate changes <span class="citation">(see, <em>e.g.</em>, McGee et al. 2014)</span>.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-25"></span>
<img src="imgs/Marsh2018_Fig4.png" alt="Proposed calibration curves in South America. Note that these are not intended to be spatially precise." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.20: Proposed calibration curves in South America. Note that these are not intended to be spatially precise.
</p>
</div>
<p>As a result, for many locations at low latitudes there will be some uncertainty about which is the appropriate calibration curve. If we don’t know, we shouldn’t pretend that we do, or we will produce inaccurate age estimates. Marsh and colleagues <span class="citation">(2018)</span> offer a practical solution that can be applied in OxCal - using a mixed curve that might be any mix of IntCal and SHCal. This will add some uncertainty to age estimates, but if we in fact aren’t sure which calibration curve is appropriate, then there should be some additional uncertainty. We can illustrate this by adding a third version of our 1100 ±40 date and specifying a mixed calibration curve. We’ll do that through the ‘Code’ view, to get an idea of what raw OxCal code looks like.</p>
</div>
</div>
<div id="oxcal-code" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> OxCal code<a href="cemetery.html#oxcal-code" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>OxCal code, called Chronological Query Language (CQL; the current version is CQL2), built on javascript. If you click on the ‘Code’ button at the bottom left of the ‘Input’ window, you’ll see this raw input, which looks like this:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb1-1"><a href="cemetery.html#cb1-1" tabindex="-1"></a> <span class="fu">Plot</span>()</span>
<span id="cb1-2"><a href="cemetery.html#cb1-2" tabindex="-1"></a> {</span>
<span id="cb1-3"><a href="cemetery.html#cb1-3" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;IntCal20&quot;</span><span class="op">,</span><span class="st">&quot;intcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb1-4"><a href="cemetery.html#cb1-4" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabID-XXX.1&quot;</span><span class="op">,</span><span class="dv">1100</span><span class="op">,</span><span class="dv">40</span>)<span class="op">;</span></span>
<span id="cb1-5"><a href="cemetery.html#cb1-5" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb1-6"><a href="cemetery.html#cb1-6" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabID-XXX.2&quot;</span><span class="op">,</span><span class="dv">1100</span><span class="op">,</span><span class="dv">40</span>)<span class="op">;</span></span>
<span id="cb1-7"><a href="cemetery.html#cb1-7" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
 Plot()
 {
  Curve("IntCal20","intcal20.14c");
  R_Date("LabID-XXX.1",1100,40);
  Curve("SHCal20","shcal20.14c");
  R_Date("LabID-XXX.2",1100,40);
 };

</script>
<p>It can be much more efficient to edit this directly once you’re familiar with OxCal code, but - as with any code language - that requires a certain level of comfort and careful attention to detail (dropping a <code>;</code> or not closing a <code>(</code> will have dire consequences). So you can see what’s possible, though, let’s add two lines: a new curve, and a third iteration of that same date.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb2-1"><a href="cemetery.html#cb2-1" tabindex="-1"></a> <span class="fu">Plot</span>()</span>
<span id="cb2-2"><a href="cemetery.html#cb2-2" tabindex="-1"></a> {</span>
<span id="cb2-3"><a href="cemetery.html#cb2-3" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;IntCal20&quot;</span><span class="op">,</span><span class="st">&quot;intcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb2-4"><a href="cemetery.html#cb2-4" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabID-XXX.1&quot;</span><span class="op">,</span><span class="dv">1100</span><span class="op">,</span><span class="dv">40</span>)<span class="op">;</span></span>
<span id="cb2-5"><a href="cemetery.html#cb2-5" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb2-6"><a href="cemetery.html#cb2-6" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabID-XXX.2&quot;</span><span class="op">,</span><span class="dv">1100</span><span class="op">,</span><span class="dv">40</span>)<span class="op">;</span></span>
<span id="cb2-7"><a href="cemetery.html#cb2-7" tabindex="-1"></a>  <span class="fu">Mix_Curve</span>(<span class="st">&quot;Mixed&quot;</span><span class="op">,</span><span class="st">&quot;IntCal20&quot;</span><span class="op">,</span><span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="fu">U</span>(<span class="dv">0</span><span class="op">,</span><span class="dv">100</span>))<span class="op">;</span></span>
<span id="cb2-8"><a href="cemetery.html#cb2-8" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabID-XXX.3&quot;</span><span class="op">,</span><span class="dv">1100</span><span class="op">,</span><span class="dv">40</span>)<span class="op">;</span></span>
<span id="cb2-9"><a href="cemetery.html#cb2-9" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
 Plot()
 {
  Curve("IntCal20","intcal20.14c");
  R_Date("LabID-XXX.1",1100,40);
  Curve("SHCal20","shcal20.14c");
  R_Date("LabID-XXX.2",1100,40);
  Mix_Curve("Mixed","IntCal20","SHCal20",U(0,100));
  R_Date("LabID-XXX.3",1100,40);
 };

</script>
<p>Running that model again will produce a third pdf; we can visualize all three with ‘View’–&gt;‘Plot dates’. To change the color of the third plot, click on the icon in the ‘Edit’ column in that row in the ‘Table’ window. The ‘Color’ field in the pop-up that appears will reocgnize basic English color names (“blue”, “red”, etc).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="imgs/oxcal/edit_color.png" alt="Changing the color of a plotted pdf." width="80%" style="float:right;padding:10px" />
<p class="caption">
Figure 5.21: Changing the color of a plotted pdf.
</p>
</div>
<p>This approach calibrates the radiocarbon determination considering what the result would be if the appropriate curve were IntCal20, SHCal20, or any mix of the two. The results, not surprisingly, look like a combination of our first two efforts. If we had other constraints affecting the age estimate, that might push the model towards preferring one curve or the other, or a particular mix. (As will become clear later, when we specify a calibration curve we are asserting a <em>prior</em>; this approach avoids that assertion).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-29"></span>
<img src="imgs/oxcal/curves_results_3.png" alt="Plotting results." width="80%" style="padding:10px" />
<p class="caption">
Figure 5.22: Plotting results.
</p>
</div>
<p>From here on, we’ll assume that our cemetery is in fact in the Chicama Valley on the Pacific Coast of Peru, where it’s clear that the southern hemisphere curve is appropriate. With that in mind, let’s return to our sample of 20 burials. This time, rather than considering age estimates based on ceramics or other diagnostic material culture from those 20 burials, we’ll examine radiocarbon dates.</p>
<p><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div id="importing-data-into-oxcal" class="section level4 hasAnchor" number="5.4.5.1">
<h4><span class="header-section-number">5.4.5.1</span> Importing data into OxCal<a href="cemetery.html#importing-data-into-oxcal" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you still have the previous model in your ‘Input’, either delete it or open a new model. Efficiently calibrating multiple dates is <em>extremely</em> useful. Open <code>bur20sim.csv</code> however you like (MS Excel or something like it will work fine). Select and copy all of the rows (excluding the column names). Return to OxCal, and in the ‘Input’ window, choose the ‘Tools’–&gt;‘Import’ dropdown (Fig. 5.23). In the ‘Import’ window that pops up, make sure that ‘Command’ is selecting “R_Date”, and ‘Separator’ is “Tab”, and paste your data into the ‘Data’ space (column order matters; OxCal expects <code>Name | Radiocarbon age | Error</code>). When you click the ‘Insert’ button, these will be added to your model at whichever dot you have selected in the ‘List’ view. Make sure that you insert a line specifying SHCal20 as the curve at the beginning (or, in the ‘List’ interface, with ‘Insert’–&gt;‘Others’–&gt;‘Curve’), so that your complete code looks like this:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb3-1"><a href="cemetery.html#cb3-1" tabindex="-1"></a>  <span class="fu">Plot</span>()</span>
<span id="cb3-2"><a href="cemetery.html#cb3-2" tabindex="-1"></a> {</span>
<span id="cb3-3"><a href="cemetery.html#cb3-3" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb3-4"><a href="cemetery.html#cb3-4" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-01&quot;</span><span class="op">,</span><span class="dv">896</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-5"><a href="cemetery.html#cb3-5" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-02&quot;</span><span class="op">,</span><span class="dv">940</span><span class="op">,</span><span class="dv">36</span>)<span class="op">;</span></span>
<span id="cb3-6"><a href="cemetery.html#cb3-6" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-03&quot;</span><span class="op">,</span><span class="dv">1188</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb3-7"><a href="cemetery.html#cb3-7" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-04&quot;</span><span class="op">,</span><span class="dv">896</span><span class="op">,</span><span class="dv">32</span>)<span class="op">;</span></span>
<span id="cb3-8"><a href="cemetery.html#cb3-8" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-05&quot;</span><span class="op">,</span><span class="dv">1106</span><span class="op">,</span><span class="dv">30</span>)<span class="op">;</span></span>
<span id="cb3-9"><a href="cemetery.html#cb3-9" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-06&quot;</span><span class="op">,</span><span class="dv">1087</span><span class="op">,</span><span class="dv">26</span>)<span class="op">;</span></span>
<span id="cb3-10"><a href="cemetery.html#cb3-10" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-07&quot;</span><span class="op">,</span><span class="dv">1012</span><span class="op">,</span><span class="dv">27</span>)<span class="op">;</span></span>
<span id="cb3-11"><a href="cemetery.html#cb3-11" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-08&quot;</span><span class="op">,</span><span class="dv">1148</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-12"><a href="cemetery.html#cb3-12" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-09&quot;</span><span class="op">,</span><span class="dv">1094</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb3-13"><a href="cemetery.html#cb3-13" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-10&quot;</span><span class="op">,</span><span class="dv">1047</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-14"><a href="cemetery.html#cb3-14" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-11&quot;</span><span class="op">,</span><span class="dv">1128</span><span class="op">,</span><span class="dv">36</span>)<span class="op">;</span></span>
<span id="cb3-15"><a href="cemetery.html#cb3-15" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-12&quot;</span><span class="op">,</span><span class="dv">990</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-16"><a href="cemetery.html#cb3-16" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-13&quot;</span><span class="op">,</span><span class="dv">951</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-17"><a href="cemetery.html#cb3-17" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-14&quot;</span><span class="op">,</span><span class="dv">1197</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb3-18"><a href="cemetery.html#cb3-18" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-15&quot;</span><span class="op">,</span><span class="dv">1134</span><span class="op">,</span><span class="dv">33</span>)<span class="op">;</span></span>
<span id="cb3-19"><a href="cemetery.html#cb3-19" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-16&quot;</span><span class="op">,</span><span class="dv">989</span><span class="op">,</span><span class="dv">30</span>)<span class="op">;</span></span>
<span id="cb3-20"><a href="cemetery.html#cb3-20" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-17&quot;</span><span class="op">,</span><span class="dv">946</span><span class="op">,</span><span class="dv">33</span>)<span class="op">;</span></span>
<span id="cb3-21"><a href="cemetery.html#cb3-21" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-18&quot;</span><span class="op">,</span><span class="dv">1185</span><span class="op">,</span><span class="dv">15</span>)<span class="op">;</span></span>
<span id="cb3-22"><a href="cemetery.html#cb3-22" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-19&quot;</span><span class="op">,</span><span class="dv">1143</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb3-23"><a href="cemetery.html#cb3-23" tabindex="-1"></a>  <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-20&quot;</span><span class="op">,</span><span class="dv">1141</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb3-24"><a href="cemetery.html#cb3-24" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
  Plot()
 {
  Curve("SHCal20","shcal20.14c");
  R_Date("LabXX-01",896,31);
  R_Date("LabXX-02",940,36);
  R_Date("LabXX-03",1188,29);
  R_Date("LabXX-04",896,32);
  R_Date("LabXX-05",1106,30);
  R_Date("LabXX-06",1087,26);
  R_Date("LabXX-07",1012,27);
  R_Date("LabXX-08",1148,31);
  R_Date("LabXX-09",1094,29);
  R_Date("LabXX-10",1047,31);
  R_Date("LabXX-11",1128,36);
  R_Date("LabXX-12",990,31);
  R_Date("LabXX-13",951,31);
  R_Date("LabXX-14",1197,29);
  R_Date("LabXX-15",1134,33);
  R_Date("LabXX-16",989,30);
  R_Date("LabXX-17",946,33);
  R_Date("LabXX-18",1185,15);
  R_Date("LabXX-19",1143,29);
  R_Date("LabXX-20",1141,31);
 };

</script>
<p>Note that the ‘Curve’ command at the beginning loads a calibration curve, which defaults to IntCal20 if you don’t specify anything. If you <em>do</em> specify a curve, OxCal (which reads from top to bottom) will keep using the last one invoked until you specify otherwise. You can call previously loaded curves using the ‘Tools’–&gt;‘Curves’ dropdown.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="imgs/oxcal/import.png" alt="Importing multiple dates." width="60%" style="padding:10px" />
<p class="caption">
Figure 5.23: Importing multiple dates.
</p>
</div>
<p>Calibrate these dates (‘Run’) and then plot them (‘View’–&gt;‘Plot dates’ and/or ‘View’–&gt;‘Plot stack’). The stack helps visualize the patterns that you may see in the individually plotted pdfs.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34-1"></span>
<img src="imgs/oxcal/simdates_plot.png" alt="Plotting multiple dates." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.24: Plotting multiple dates.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34-2"></span>
<img src="imgs/oxcal/simdates_stack.png" alt="Plotting multiple dates." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.25: Plotting multiple dates.
</p>
</div>
<p>Using these plots of calibrated dates, let’s return to our questions about the cemetery:</p>
<ul>
<li>When did use as a cemetery begin?</li>
<li>For how long was the area used as a cemetery?</li>
<li>When did use as a cemetery end?</li>
<li>Was there a period of more intense use, and if so when and for how long?</li>
</ul>
</div>
<div id="visual-inspection-of-calibrated-14c-determinations." class="section level4 hasAnchor" number="5.4.5.2">
<h4><span class="header-section-number">5.4.5.2</span> Visual inspection of calibrated <span class="math inline">\(^{14}C\)</span> determinations.<a href="cemetery.html#visual-inspection-of-calibrated-14c-determinations." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As Bayliss and colleagues <span class="citation">(2007, 8–9)</span> discuss in detail, visual inspection of assemblages of radiocarbon dates almost inevitably leads to overestimation of the spans of time that produced those assemblages. If we take the maximum and minimum of the 95% HDRs, we get 685 - 1221. A similar but less precise estimate - the one most archaeologists would probably give - based on visual inspection of the calibrated ranges would likely be something like, “about 850 CE to a bit after 1200 CE”.</p>
<p><span style="color: red;">But in fact our simulated <span class="math inline">\(^{14}C\)</span> ages are from samples drawn from a uniform distribution covering the interval <strong>800 - 1100 CE</strong>.</span></p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-36"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-36-1.png" alt="Calendar dates and simulated radiocarbon dates." width="672" />
<p class="caption">
Figure 5.26: Calendar dates and simulated radiocarbon dates.
</p>
</div>
</div>
<div id="phase_models" class="section level4 hasAnchor" number="5.4.5.3">
<h4><span class="header-section-number">5.4.5.3</span> Bounded Phase models in OxCal<a href="cemetery.html#phase_models" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This problem of overestimation stems from the visual impact of the uncertainty plotted as the pdf of a calibrated date, which is often (mis)interpreted as a span of time rather than a distribution of probability. That is, if we treated these distributions as indicated a span <em>within which</em> activity occurred, we’d probably be mostly right. When we try to interpret it as a span that indicates when use began and ended, then we’re very likely to be wrong. OxCal addresses this problem of overestimation with the ‘bounded phase model’. A bounded phase model treats the specified dates as a sample drawn from (by default) a uniform distribution that is defined by the boundaries. In practice this means taking into account the fact that a) the limited precision with which we can describe dates produces additional scatter, and b) it’s unlikely to draw many samples from the extremes of a distribution. This assertion of a <em>uniform prior</em> is fundamental to OxCal’s logic, and underlies some of its most important results: improved estimation of timespans in the vast majority of cases. If we have no basis from which to assert some other parent distribution of our samples, then a uniform (“uninformative”) prior is very likely the best choice. However, if there’s reason to think that another prior better describes the population of dateable events that we have sampled - in our cemetery case, we might for instance suspect based on ceramic styles that the frequency of interments increased over time - then it’s a good idea to explicitly incorporate that information by asserting it as a prior (i.e., by modeling a non-uniform phase; more on that later).</p>
<blockquote>
<p>It almost certainly gives us a more realistic interpretation of the given information although we have made an extra (and possibly difficult to substantiate) assumption. To use no model at all is in fact to assume that all of the events are truly independent; this is in effect a model in itself, and in many cases a very unreasonable one. <span class="citation">(Bronk Ramsey 1998)</span></p>
</blockquote>
<p>In practice this means adding three commands (incidentally, you can review OxCal’s commands by selecting ‘Help’ and then ‘Command reference’): <code>Sequence</code>, <code>Boundary</code>, and <code>Phase</code>. <code>Sequence</code> asserts that the events that follow (within the <code>{}</code> that follow, in the code) are in chronological sequence; <code>Boundary</code> commands are used in pairs to define the events that should be considered as sampled from a discrete distribution (by default a uniform one, as noted above); <code>Phase</code> describes (also within the <code>{}</code>that follow) events whose relative sequence is unknown (if we knew - based on, <em>e.g.</em>, stylistic grounds - that one dated burial was the earliest, we could place it before the <code>Phase</code> command in the sequence). So, the entire sequence laid out below can be read as, “here are a pair of sequential boundaries; these describe a collection of dated events (whose relative sequence is entirely unknown) as a random sample from a uniform distribution of dateable events”.</p>
<p>You can build a bounded phase model from scratch by using the ‘Insert’ button in the ‘Input’ window and/or by editing the code directly. You can also ‘Tools’–&gt;‘Models’–&gt;‘Phases’ to insert the entire structure (Sequence, Boundaries, and Phase), and then populate that with dates. That structure (including a line establishing that we will use SHCal20), looks like this, for a phase called “Cem 1”:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb4-1"><a href="cemetery.html#cb4-1" tabindex="-1"></a> <span class="fu">Plot</span>()</span>
<span id="cb4-2"><a href="cemetery.html#cb4-2" tabindex="-1"></a> {</span>
<span id="cb4-3"><a href="cemetery.html#cb4-3" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb4-4"><a href="cemetery.html#cb4-4" tabindex="-1"></a>  <span class="fu">Sequence</span>()</span>
<span id="cb4-5"><a href="cemetery.html#cb4-5" tabindex="-1"></a>  {</span>
<span id="cb4-6"><a href="cemetery.html#cb4-6" tabindex="-1"></a>   <span class="fu">Boundary</span>(<span class="st">&quot;Start Cem 1&quot;</span>)<span class="op">;</span></span>
<span id="cb4-7"><a href="cemetery.html#cb4-7" tabindex="-1"></a>   <span class="fu">Phase</span>(<span class="st">&quot;Cem 1&quot;</span>)</span>
<span id="cb4-8"><a href="cemetery.html#cb4-8" tabindex="-1"></a>   {</span>
<span id="cb4-9"><a href="cemetery.html#cb4-9" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb4-10"><a href="cemetery.html#cb4-10" tabindex="-1"></a>   <span class="fu">Boundary</span>(<span class="st">&quot;End Cem 1&quot;</span>)<span class="op">;</span></span>
<span id="cb4-11"><a href="cemetery.html#cb4-11" tabindex="-1"></a>  }<span class="op">;</span></span>
<span id="cb4-12"><a href="cemetery.html#cb4-12" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
 Plot()
 {
  Curve("SHCal20","shcal20.14c");
  Sequence()
  {
   Boundary("Start Cem 1");
   Phase("Cem 1")
   {
   };
   Boundary("End Cem 1");
  };
 };
</script>
<p>Move your radiocarbon dates (all the <code>R_Date();</code> lines) so that they are inside the Phase command. Before we run the model we’ll also add two <em>queries</em> that will make it easier to assess the results: a <code>KDE_Plot</code> command (found under ‘Insert’, then ‘Models’), and an <code>Interval</code> command, both of which should be placed inside the <code>Phase</code> command. <code>Interval</code> will estimate the span of time between the boundaries, and <code>KDE_Plot</code> will produce a summary of the dated events in the phase. Your complete code should look like this:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb5-1"><a href="cemetery.html#cb5-1" tabindex="-1"></a> <span class="fu">Plot</span>()</span>
<span id="cb5-2"><a href="cemetery.html#cb5-2" tabindex="-1"></a> {</span>
<span id="cb5-3"><a href="cemetery.html#cb5-3" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb5-4"><a href="cemetery.html#cb5-4" tabindex="-1"></a>  <span class="fu">Sequence</span>()</span>
<span id="cb5-5"><a href="cemetery.html#cb5-5" tabindex="-1"></a>  {</span>
<span id="cb5-6"><a href="cemetery.html#cb5-6" tabindex="-1"></a>   <span class="fu">Boundary</span>(<span class="st">&quot;Start Cem 1&quot;</span>)<span class="op">;</span></span>
<span id="cb5-7"><a href="cemetery.html#cb5-7" tabindex="-1"></a>   <span class="fu">Phase</span>(<span class="st">&quot;Cem 1&quot;</span>)</span>
<span id="cb5-8"><a href="cemetery.html#cb5-8" tabindex="-1"></a>   {</span>
<span id="cb5-9"><a href="cemetery.html#cb5-9" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-01&quot;</span><span class="op">,</span><span class="dv">896</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-10"><a href="cemetery.html#cb5-10" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-02&quot;</span><span class="op">,</span><span class="dv">940</span><span class="op">,</span><span class="dv">36</span>)<span class="op">;</span></span>
<span id="cb5-11"><a href="cemetery.html#cb5-11" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-03&quot;</span><span class="op">,</span><span class="dv">1188</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb5-12"><a href="cemetery.html#cb5-12" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-04&quot;</span><span class="op">,</span><span class="dv">896</span><span class="op">,</span><span class="dv">32</span>)<span class="op">;</span></span>
<span id="cb5-13"><a href="cemetery.html#cb5-13" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-05&quot;</span><span class="op">,</span><span class="dv">1106</span><span class="op">,</span><span class="dv">30</span>)<span class="op">;</span></span>
<span id="cb5-14"><a href="cemetery.html#cb5-14" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-06&quot;</span><span class="op">,</span><span class="dv">1087</span><span class="op">,</span><span class="dv">26</span>)<span class="op">;</span></span>
<span id="cb5-15"><a href="cemetery.html#cb5-15" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-07&quot;</span><span class="op">,</span><span class="dv">1012</span><span class="op">,</span><span class="dv">27</span>)<span class="op">;</span></span>
<span id="cb5-16"><a href="cemetery.html#cb5-16" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-08&quot;</span><span class="op">,</span><span class="dv">1148</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-17"><a href="cemetery.html#cb5-17" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-09&quot;</span><span class="op">,</span><span class="dv">1094</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb5-18"><a href="cemetery.html#cb5-18" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-10&quot;</span><span class="op">,</span><span class="dv">1047</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-19"><a href="cemetery.html#cb5-19" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-11&quot;</span><span class="op">,</span><span class="dv">1128</span><span class="op">,</span><span class="dv">36</span>)<span class="op">;</span></span>
<span id="cb5-20"><a href="cemetery.html#cb5-20" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-12&quot;</span><span class="op">,</span><span class="dv">990</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-21"><a href="cemetery.html#cb5-21" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-13&quot;</span><span class="op">,</span><span class="dv">951</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-22"><a href="cemetery.html#cb5-22" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-14&quot;</span><span class="op">,</span><span class="dv">1197</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb5-23"><a href="cemetery.html#cb5-23" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-15&quot;</span><span class="op">,</span><span class="dv">1134</span><span class="op">,</span><span class="dv">33</span>)<span class="op">;</span></span>
<span id="cb5-24"><a href="cemetery.html#cb5-24" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-16&quot;</span><span class="op">,</span><span class="dv">989</span><span class="op">,</span><span class="dv">30</span>)<span class="op">;</span></span>
<span id="cb5-25"><a href="cemetery.html#cb5-25" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-17&quot;</span><span class="op">,</span><span class="dv">946</span><span class="op">,</span><span class="dv">33</span>)<span class="op">;</span></span>
<span id="cb5-26"><a href="cemetery.html#cb5-26" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-18&quot;</span><span class="op">,</span><span class="dv">1185</span><span class="op">,</span><span class="dv">15</span>)<span class="op">;</span></span>
<span id="cb5-27"><a href="cemetery.html#cb5-27" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-19&quot;</span><span class="op">,</span><span class="dv">1143</span><span class="op">,</span><span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb5-28"><a href="cemetery.html#cb5-28" tabindex="-1"></a>    <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-20&quot;</span><span class="op">,</span><span class="dv">1141</span><span class="op">,</span><span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb5-29"><a href="cemetery.html#cb5-29" tabindex="-1"></a>    <span class="fu">KDE_Plot</span>(<span class="st">&quot;Cem 1 KDE&quot;</span>)<span class="op">;</span></span>
<span id="cb5-30"><a href="cemetery.html#cb5-30" tabindex="-1"></a>    <span class="fu">Interval</span>(<span class="st">&quot;Cem 1 interval&quot;</span>)<span class="op">;</span></span>
<span id="cb5-31"><a href="cemetery.html#cb5-31" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb5-32"><a href="cemetery.html#cb5-32" tabindex="-1"></a>   <span class="fu">Boundary</span>(<span class="st">&quot;End Cem 1&quot;</span>)<span class="op">;</span></span>
<span id="cb5-33"><a href="cemetery.html#cb5-33" tabindex="-1"></a>  }<span class="op">;</span></span>
<span id="cb5-34"><a href="cemetery.html#cb5-34" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
 Plot()
 {
  Curve("SHCal20","shcal20.14c");
  Sequence()
  {
   Boundary("Start Cem 1");
   Phase("Cem 1")
   {
    R_Date("LabXX-01",896,31);
    R_Date("LabXX-02",940,36);
    R_Date("LabXX-03",1188,29);
    R_Date("LabXX-04",896,32);
    R_Date("LabXX-05",1106,30);
    R_Date("LabXX-06",1087,26);
    R_Date("LabXX-07",1012,27);
    R_Date("LabXX-08",1148,31);
    R_Date("LabXX-09",1094,29);
    R_Date("LabXX-10",1047,31);
    R_Date("LabXX-11",1128,36);
    R_Date("LabXX-12",990,31);
    R_Date("LabXX-13",951,31);
    R_Date("LabXX-14",1197,29);
    R_Date("LabXX-15",1134,33);
    R_Date("LabXX-16",989,30);
    R_Date("LabXX-17",946,33);
    R_Date("LabXX-18",1185,15);
    R_Date("LabXX-19",1143,29);
    R_Date("LabXX-20",1141,31);
    KDE_Plot("Cem 1 KDE");
    Interval("Cem 1 interval");
   };
   Boundary("End Cem 1");
  };
 };
</script>
<p>Once you’ve run the model, two aspects of the results are important to review: 1) the effects of the model on the estimated ranges for each radiocarbon date, and 2) the estimated parameters for the phase as a whole. Select ‘View’–&gt;‘Plot dates’ to review the results (you may need to select ‘Edit’–&gt;‘Adjust’ to change the plot size).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-39"></span>
<img src="imgs/oxcal/phase_model_plot.png" alt="Plotting a phase model." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.27: Plotting a phase model.
</p>
</div>
<p>You’ll notice that each radiocarbon date is now described by two superimposed pdfs. In <span style="color: lightgrey;"><strong>grey</strong></span> is the calibrated date (the “prior distribution”, because it was the information that we used as <em>input</em> for our model), and in <span style="color: black;"><strong>black</strong></span> is the modeled result (the <em>posterior distribution</em>, because it is calculated by revising the priors according to model parameters). We have used few priors here, so the differences we’re seeing between prior and posterior distributions reflect only the effects of the bounded phase model: the early and late extremes are constrained, correcting for the scatter introduced by imprecision. We can best review the results for the phase as a whole by limiting the plot to just the key items. Return to the ‘Table’ window, and, using the check-boxes in the ‘Select’ column, select <em>only</em> the boundaries and the KDE_Plot. I like to change the colors of the boundaries as well, to distinguish them. The KDE is a modeled approximation of the distribution from which our dated events came <span class="citation">(Bronk Ramsey 2017b)</span> (a formal version of the stacked plot). The black <span style="color: black;"><strong>‘+’</strong></span> below are the medians of the posterior distributions that go into it, and the grey <span style="color: lightgrey;"><strong>‘+’</strong></span> below (hard to see on the blue background in the default color scheme) are the medians of the unmodeled dates. The boundaries are modeled estimates of the beginning and terminus of the parent distribution - remember that we’re using our dated events to try to reconstruct the <em>population</em> of dated events which we’ve sampled, which is to say all the potentially dateable events; in the case of our cemetery, all the interments. Like the pdf that described an individual calibrated date, these are curves describing the uncertainty with which we can estimate these dates. So, referencing Figure 5.28 and the ‘Table’ window, we can say with 95% confidence that our phase began between 850 and 965 CE (rounding a bit), and ended between 1060 and 1250 CE.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="imgs/oxcal/phase_model_KDE.png" alt="KDE and boundaries." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.28: KDE and boundaries.
</p>
</div>
<p>If you look at the results of the ‘Interval’ query in the ‘Table’ window, you’ll find that the 95% confidence interval is 113-381 years, with a median of 276 years. That is a corollary of the boundaries, and the phase model’s answer to our question of how long the cemetery was in use. It varies quite a bit for two reasons: we don’t have a huge number of samples, and we have no information with which to constrain the initial and terminal dates (no dated events that predate and postdate cemetery use). If we could add those, our estimate would get more precise.</p>
<p>How good are our results? Well, if we take the medians of the boundaries (not ideal for describing the bimodal distribution of the end boundary, but efficient), we’d say that our phase began around 900 CE and lasted until about 1180 CE. The end might come with a caveat: there’s a good chance that it’s about 90 years earlier; we can tell from the KDE that really there are only one or two dates that are pushing our end date forward. Knowing as we do that our initial dated events were sampled from a uniform distribution extending from 800-1100 CE, we can tell that we are victims of some bad luck in our sampling. We haven’t sampled any early burials, and we got one late date that seems to be the result of a radiocarbon age intersecting a wide calibrated range (see Figure 5.26; these are likely LabXX-02 and LabXX-04). The problem, of course, that if we weren’t working from simulated data, we’d have no way to know that our results were inaccurate - a good illustration of the kinds of uncertainties that are difficult to escape in any chronological model.</p>
<p>####Simulating radiocarbon samples in OxCal</p>
<p>If you want to explore these uncertainties further, you can re-run this example with different simulated dates. The <code>R_Simulate</code> command in OxCal randomly generates a radiocarbon age that <em>might result</em> from a given calendar age.</p>
<div id="example-code" class="section level7" number="5.4.5.3.0.0.1">
<p class="heading"><span class="header-section-number">5.4.5.3.0.0.1</span> example code</p>
</div>
</div>
</div>
<div id="introducing-real-world-complications" class="section level3 hasAnchor" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Introducing real-world complications<a href="cemetery.html#introducing-real-world-complications" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So far we have ignored a fundamental question: <em>what have we dated?</em></p>
<p>The question of what we have dated is on its face a question about material: which materials - of the variety available, illustrated in Figure 5.4 - were sampled and sent for radiocarbon analysis? More fundamentally, it is a question about the relationship between <em>target event</em> and <em>dated event</em>. That is, a) what is the event whose date we are attempting to estimate, b) what is the event whose radiocarbon age is measured, and c) are (a) and (b) the same? Given the <a href="cemetery.html#cemetery">questions that we have framed about the cemetery</a>, (a) is the moment of interment: we are hoping that the radiocarbon ages that we get on samples from various burials will tell us relatively precisely when those individuals were buried. What (b) is depends very much on the specific sample; it might match (a) closely, or diverge by as much as centuries.</p>
<p>The problem is not unique to radiocarbon: typological dating of an interment can be confounded by the use of heirloom objects as burial goods, for example, while secondary burial and tomb-reentry are fundamentally challenges that should be met through methods of excavation (and documentation).</p>
<p>Three types of problems are most common: old wood, residence time, and marine reservoir effects.</p>
<div id="old-wood" class="section level4 hasAnchor" number="5.4.6.1">
<h4><span class="header-section-number">5.4.6.1</span> old wood<a href="cemetery.html#old-wood" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Trees are often long-lived organisms whose growth occurs in discrete (often but not necessarily annual) increments - tree rings. Their tissue incorporates atmospheric carbon through photosynthesis across the entire lifespan of the tree; each ring is in equilibrium with atmospheric carbon at the time that it is formed. In consequence, interior rings will have a radiocarbon age (and in fact a calendar age) greater than that of exterior rings. In the case of wood recovered in archaeological context (<em>e.g.</em>, timber in construction), the date of interest is usually the moment of harvest. Unless the outermost rings (or small twigs) are sampled, however, there is a risk that the estimated age may be much older - as much as centuries older, in the case of long-lived species. In Figure 5.29, a sample from rings laid down around 570 CE would (and should!) have a very different radiocarbon age than a sample from rings laid down around 1492 CE.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-41"></span>
<img src="imgs/bigbasin_redwood.png" alt="Cross-section of a California redwood (*Sequoia sempervirens*) that sprouted in 544 CE and fell in 1936 CE. A 1cm$^{3}$ wood sample from near the center of the trunk would - accurately - produce a radiocarbon age &gt;1000 years older than one near the bark." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.29: Cross-section of a California redwood (<em>Sequoia sempervirens</em>) that sprouted in 544 CE and fell in 1936 CE. A 1cm<span class="math inline">\(^{3}\)</span> wood sample from near the center of the trunk would - accurately - produce a radiocarbon age &gt;1000 years older than one near the bark.
</p>
</div>
</div>
<div id="residence-time" class="section level4 hasAnchor" number="5.4.6.2">
<h4><span class="header-section-number">5.4.6.2</span> residence time<a href="cemetery.html#residence-time" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The issue of residence time is often conflated with the problem of old wood, but is in fact a distinct confounding factor for age estimates. Problems of residence time stem from the persistence of organic materials on the landscape for significant spans of time after the death of the source organism, before incorporation into cultural contexts. Particularly in arid environments, carbonized, woody, and/or even herbaceous tissue can preserve very well and be available for collection for decades or even centuries. These preserved materials can either be deliberately harvested and incorporated into cultural deposits, or can be incidentally harvested when other materials are collected.</p>
</div>
<div id="marine-reservoir" class="section level4 hasAnchor" number="5.4.6.3">
<h4><span class="header-section-number">5.4.6.3</span> marine reservoir<a href="cemetery.html#marine-reservoir" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Note that the illustration of the carbon cycle (Figure 5.5) includes exchange between ocean and atmosphere. This exchange, because oceans constitute a much greater proportion of the southern hemisphere than the northern, is a contributor to the <a href="cemetery.html#curves">contrast in atmospheric <span class="math inline">\(^{14}C\)</span> between hemispheres</a>. The amount of ocean-atmosphere exchange is significant because the oceans (and other bodies of water, though we won’t cover freshwater here) contain “old” carbon, which is to say carbon &gt;55kya, with no <span class="math inline">\(^{14}C\)</span> remaining. Globally, surface water in the oceans is ~400 radiocarbon years older than the atmosphere; where upwelling introduces deeper water and correspondingly more old carbon, the offset can be greater. The age of marine carbon can have both direct and indirect impacts on radiocarbon ages of archaeological materials. Organisms that derive some or all of the carbon in their tissues from marine rather than atmospheric sources will be incorporating carbon with greater apparent age. If the offset between marine carbon and atmospheric carbon at the time and place of tissue formation were known, it would be straightforward to calculate the calendar age of a sample even if its carbon were marine in origin. Complications arise because the offset between marine and atmospheric carbon is variable in space and time, and because organisms may incorporate carbon from a mixture of different reservoirs. Ideally this is managed by establishing the local offset from the global marine average (the Marine20 calibration curve <span class="citation">(Heaton et al. 2020)</span>) for the period of interest. Establishing that globally, even for recent times, is complicated by post-1945 atomic testing. A regularly updated database of radiocarbon measuremnts on pre-bomb marine samples of known age <span class="citation">(Reimer and Reimer 2001)</span> is available at <a href="http://calib.org/marine/">calib.org</a>. It is, however, sparse for many regions globally, including coastal Peru (Figure 5.30). It alo consists primarily of early <span class="math inline">\(20^{th}\)</span>-century materials, meaning that it cannot account for past variations in <span class="math inline">\(\Delta{R}\)</span>. Since <span class="math inline">\(\Delta{R}\)</span> is sensitive to strength of upwelling, past variation is to be expected, particularly given the effects of ENSO on upwelling off the coast of western South America <span class="citation">(Jones et al. 2010)</span>.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-42"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-42-1.png" alt="Data in calib.org/marine for coastal Peru, as of 08/2024." width="672" />
<p class="caption">
Figure 5.30: Data in calib.org/marine for coastal Peru, as of 08/2024.
</p>
</div>
<p>The preferred solution for archaeological questions is to date paired marine and terrestrial samples from the region and time period of interest - that is, from the same context and believed to be of the same age - in order to directly establish the relevant <span class="math inline">\(\Delta{R}\)</span>. While this should improve age estimates, however, the multiple uncertainties involved in such a project are likely to make dating samples with marine reservoir offsets useful only if the underlying chronological questions do not require high precision. Bayliss and Marshall <span class="citation">(2022, 40)</span> go so far as to drily advise that, “the best policy for dealing with samples that exhibit reservoir effects is avoidance”.</p>
<p><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-43-1.png" width="672" /><img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-43-2.png" width="672" /></p>
<pre><code>## [1] 21.0 48.9</code></pre>
<div id="diet" class="section level5 hasAnchor" number="5.4.6.3.1">
<h5><span class="header-section-number">5.4.6.3.1</span> dietary offsets<a href="cemetery.html#diet" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Marine reservoir effects impact more than just marine organisms. Animals - including humans - derive the carbon used to build tissue from the the organisms that they consume (similarly, marine and aquatic plants, if even partially submerged, are likely to derive at least some of their carbon from non-atmospheric reservoirs). Animals that consume marine organisms thus derive some of their carbon from marine reservoirs. If 50% of their diet is marine, then 50% of their carbon will be marine, and the appropriate calibration curve would be a 50/50 mix of atmospheric (IntCal20 or SHCal20) and marine (Marine20, adjusted for local <span class="math inline">\(\Delta{R}\)</span>). Estimating the dietary inputs of the organism from which a dated sample is derived can thus be a key consideration. This is most commonly an issue for dates on human tissue in coastal settings. In such cases either greater uncertainty has to be built into the age estimate, or some approximation of the relative contribution of different reservoirs established. The latter generally is derived from measurements of stable carbon and nitrogen isotopes <span class="citation">(Richards 2020)</span>, which in combination are used to estimate long-term sources of dietary protein (Figure 5.31) using mixing models (e.g., the <em>R</em> packages <strong>simmr</strong> <span class="citation">(Govan and Parnell 2024)</span> and <strong>MixSIAR</strong> <span class="citation">(Stock et al. 2018)</span>).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-44"></span>
<img src="imgs/dietary_estimation.png" alt="Proportion of diet derived from marine sources can be estimated using C and N isotopes." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.31: Proportion of diet derived from marine sources can be estimated using C and N isotopes.
</p>
</div>
<p>Because these estimates come with their own uncertainties - a typical output of a mixing model is an estimate of % marine contribution to diet something like “42 ±25” - they tend to produce age estimates that, while more accurate than those calculated with the wrong curve, are less precise. Consider, for example, the first of the simulated dates that we have used above (LabXX-01): for a calendar age of 1074 CE we generated a simulated <span class="math inline">\(^{14}C\)</span> age of 925 ±28 using a southern hemisphere reservoir, which we calibrated with SHCal20 to produce a 95% HDR of 1052 - 1269 CE (Figure 5.32).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-45"></span>
<img src="radiocarbon_workshop_files/figure-html/unnamed-chunk-45-1.png" alt="Calendar age of 1074 CE, simulated $^{14}C$ age of 925 ±28, calibrated with SHCal20." width="672" />
<p class="caption">
Figure 5.32: Calendar age of 1074 CE, simulated <span class="math inline">\(^{14}C\)</span> age of 925 ±28, calibrated with SHCal20.
</p>
</div>
<p>What if we instead consider sample LabXX-01 to be a sample of human bone, from an individual whose diet was 50% marine, who died in 1074 CE?</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-46"></span>
<img src="imgs/oxcal/simdates_marinesim.png" alt="Effects of 50% marine diet on a calibrated age estimate." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.33: Effects of 50% marine diet on a calibrated age estimate.
</p>
</div>
<p>Introducing reservoir complications obviously degrades the precision of any age estimate - and this is assuming that we <em>know</em> the % marine diet and the local <span class="math inline">\(\Delta{R}\)</span>! In fact we should probably consider scenarios where the sample incorporates at least some carbon from the marine reservoir, <em>but we don’t know how much</em> and we may not not know the right correction to apply (i.e., the local <span class="math inline">\(\Delta{R}\)</span>). Let’s examine three scenarios where the dated individual died in 1074 CE, and consumed a diet that was 50% marine:</p>
<ul>
<li>We don’t know anything about this individual’s diet, but either consider a marine dietary component <em>unlikely</em> or simply don’t consider the issue at all, and calibrate the radiocarbon result using only the atmospheric curve (SHCal20, in this case), as we would for any other terrestrial sample. (Figure 5.34, 01a)</li>
<li>We don’t know anything about this individual’s diet, but consider it <em>likely</em> that they had a significant marine dietary component, and realize that our calibration should account for this. We know the local <span class="math inline">\(\Delta{R}\)</span> is -200 ±75 years, and can thus model the effects of a diet that might range anywhere from 0 - 100% marine. (Figure 5.34, 01b)</li>
<li>Based on the C/N isotopic composition of the sampled bone and the application of a mixing model, we are able to estimate that their diet was 50 ±20% marine, and we know the local <span class="math inline">\(\Delta{R}\)</span> is -200 ±75 years. (Figure 5.34, 01c)</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-47"></span>
<img src="imgs/oxcal/simdates_marinesim_calib.png" alt="Effects of different assumptions about a 50% marine diet on a calibrated age estimate." width="100%" style="padding:10px" />
<p class="caption">
Figure 5.34: Effects of different assumptions about a 50% marine diet on a calibrated age estimate.
</p>
</div>
<p>It should be clear that the worst possible scenario is one where we make the wrong assumption about the reservoir effects in this sample. In that case (01a), we get a relative precise answer…but one that is significantly inaccurate. For an individual that died in 1074 CE, we produce an estimate with a median of 943 CE and a 95% HDR of 889-995 (92%) and 1006-1017 (4%). In contrast, if we can approximate the marine dietary input (01c), we can produce an <em>accurate</em> result, but one that - as a result of accumulating uncertainties - is of notably low precision (median of 1088 CE and a 95% HDR of 905-923 (1%) and 963-1255 (4%)). In case we know even less about diet and/or local <span class="math inline">\(\Delta{R}\)</span>, we can produce an estimate that is accurate but even less precise (01b).</p>
<p>Bayliss and Marshall’s <span class="citation">(2022, 40)</span> dictum - “the best policy for dealing with samples that exhibit reservoir effects is avoidance” - begins to look even more reasonable. However, we may find ourselves with few other options when it comes to dateable material, or may wish to work with legacy dates, so avoidance is not always an option. Being explicit about what we know and don’t know about a given sample is, as a result, crucial to understanding how to interpret an age estimate.</p>
</div>
</div>
<div id="dated-event-vs.-target-event" class="section level4 hasAnchor" number="5.4.6.4">
<h4><span class="header-section-number">5.4.6.4</span> <em>dated event</em> vs. <em>target event</em><a href="cemetery.html#dated-event-vs.-target-event" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The accuracy and precision with which we can use radiocarbon to estimate the age of an event (by, <em>e.g.</em>, selecting the appropriate calibration curve) is only one of the relevant challenges. Understanding just which event it is whose age we have estimated, and how that age relates to the one in which we are in fact interested, is a fundamental (and under-appreciated) challenge.</p>
<p>Recall our two key questions:</p>
<ol style="list-style-type: decimal">
<li>What is the event whose age we wish to know (the <em>target event</em>)?</li>
<li>For which materials from this context might we be able to estimate an age using radiocarbon?</li>
</ol>
<p>We can add a third crucial question:</p>
<details>
<summary>
<b>3. What event will we be dating if we produce a radiocarbon age estimate of a particular material (the <em>dated event</em>)?</b>
</summary>
<p>One of the basic principles of radiocarbon dating is that the <em>dated event</em> will be the moment when the organism ceased incorporating atmospheric carbon into tissue. That is generally glossed as the death of the organism (though reality can be messier).</p>
</details>
<p>What would be the likely dated events for the various materials in Burial 11/92? How do they relate to the moment of interment (which, we have asserted above, is the event of archaeological interest [i.e., the <em>target event</em>])?</p>
<details>
<summary>
<i>- ceramics </i>
</summary>
<p>A radiocarbon date will give the date of harvest of any plant matter used as temper and/or organic residues absorbed when the vessel was used to store or cook organic materials. If the date is a bulk date (i.e., on all organic material in the sherd, combined), it will not be possible to tell which of these is contributing to the result. If residues include marine (or freshwater) products, marine (or freshwater) reservoir effects may have to be considered.</p>
</details>
<details>
<summary>
<i>- gourd (<em>Lagenaria siceraria</em>) </i>
</summary>
<p>A radiocarbon date will give the date of harvest of the gourd. Assessment of how likely that date is to be close in time to the moment of interment will be required.</p>
</details>
<details>
<summary>
<i>- textile fragment </i>
</summary>
<p>A radiocarbon date will give the date of harvest of the fibers used in manufacturing the textile. How long are fibers likely to be stored after harvest, and how long before incorporation into a burial are textiles likely to be manufactured? A textile produced for a funerary bundle will give a different date than a textile repurposed as a shroud…or an heirloom textile.</p>
</details>
<details>
<summary>
<i>- wood (algarrobo, <em>Prosopis pallida</em>) </i>
</summary>
<p>A radiocarbon date will give an average of the dates on which the growth rings that constitute the sample were formed. If an exterior ring is sampled and the trunk or branch was harvested while living, this will be the date of harvest. If interior rings are sampled and/or the wood was already dead when harvested and/or the wood was used for some span of time post-harvest but pre-burial, the dated event may be as much as centuries before interment.</p>
</details>
<details>
<summary>
<i>- marine shell </i>
</summary>
<p>The carbon in marine shell is derived from marine sources, and so a radiocarbon determination on marine shell should be calibrated using the Marine20 curve <span class="citation">(Heaton et al. 2020)</span> rather than IntCal20 or SHCal20, plus any additional local <span class="math inline">\({\Delta}R\)</span> correction available. If a local correction is available, a date on marine shell should produce an accurate calibrated result that reflects the date of death of the organism. How close the date of death is to the date of deposition will likely depend on the use to which the shell was put (consider the likely difference, for example, between <em>Donax spp.</em> and <em>Spondylus spp.</em> in this context).</p>
</details>
<details>
<summary>
<i>- human bone </i>
</summary>
<p>Burial 11/92 appears to contain not only a individual and associated material culture, but also additional long bones. While the primary individual likely died not long before burial - though this is an assumption worth examining - additional skeletal elements (like a secondary burial) may have already been old at the time of interment. Understanding the depositional history of the material we are sampling may thus be crucial to assessing the relationship between dated event and target event (and so making accurate age estimates). In the case of human bone, age and dietary offsets may also have to be considered.</p>
<p><em>age offset</em></p>
<p>Age-at-death offsets result from the persistence in bone collagen of carbon derived from materials consumed over several years or even decades before the death of the organism (i.e., bone collagen is not a snapshot of the carbon consumed immediately before the moment of death). If an organism is sufficiently old (more than ~3 decades), carbon in bone collagen may not be in equilibrium with atmospheric carbon at the time of death. However, we are rarely working at a level of precision sufficiently high for such offsets to be relevant.</p>
<p><em>dietary offset</em></p>
<p>As detailed <a href="cemetery.html#diet">above</a>, where an individual’s diet has incorporated marine protein, the carbon in their tissue will be derived from marine as well as atmospheric reservoirs, and calibration with a mixed curve - as well as accounting for any local <span class="math inline">\(\Delta{R}\)</span> - will be necessary. Even where all these parameters are known, the resulting estimate will likely be less precise than for a sample for which only the atmospheric reservoir has to be taken into account.</p>
</details>
<details>
<summary>
<i>- camelid bone </i>
</summary>
<p>As with human bone, the first question with respect to faunal bone will be how the dated event - death of the animal - relates to the moment of deposition.</p>
<p>Note that not all faunal bone should be considered comparable. Marine mammals - or terrestrial mammals consuming marine products - will have dietary offsets. In cases where individuals are mature and species are long-lived (more than a few decades), age offsets (see above) may also be relevant.</p>
</details>
<details>
<summary>
<i>- caña brava (<em>Gynerium sagittatum</em>) </i>
</summary>
<p>A radiocarbon date will give the date of harvest of the cane. Assessment of how likely that date is to be close in time to the moment of interment will be required.</p>
</details>
<details>
<summary>
<i>- unidentified wood charcoal </i>
</summary>
<p>A radiocarbon date will give an average of the dates on which the growth rings that constitute the sample were formed. If an exterior ring is dated and the trunk or branch was harvested while living, this will be the date of harvest. If interior rings are sampled and/or the wood was already dead when harvested and/or the wood was used for some span of time post-harvest but pre-carbonization and/or the burn event predated the burial event, the dated event may be as much as centuries before interment.</p>
</details>
<p>Understanding what the dated event is and assessing how it related to the target event is fundamental to accurate age estimates. If the difference between dated event and target event is known or can be estimated, then a radiocarbon determination can still produce a useful age estimate. If the difference between the two is unknown, then the radiocarbon determination can only provide an uncertain age estimate, one that accounts for the greatest possible offset between dated event and target event. Suppose for example that the burial described above turns out to also contain a wooden figurine (Figure 5.35). In order to accurately estimate the moment of deposition from a radiocarbon age estimate of that wood, we would need to estimate 1) the age of the wood when harvested (i.e., which part of the tree was used, and how old that wood might have been), 2) the amount of time that passed between the death of the tree (if it preceded harvest), harvest of the wood, and the carving of the object, and 3) the amount of time elapsed between carving of the figurine and its deposition in the burial. This is asking a lot - but if we <em>could</em> estimate those, we could adjust the radiocarbon age by applying an estimated offset, and come up with an estimated date of deposition. As with dietary offsets for bone samples, applying an age offset is likely to incorporate additional uncertainty, and consequently reduce the precision of our age estimate.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-48"></span>
<img src="imgs/brokenear.png" alt="Wooden figurine." width="206" style="float:right; padding:10px" />
<p class="caption">
Figure 5.35: Wooden figurine.
</p>
</div>
<p>(In fact, examining Figure 5.35 might lead you to suspect that, on stylistic grounds, the figurine <em>postdated</em> the burial, arguing for some post-depositional disturbance - but never mind; that’s not our point here.)</p>
<p>The decision trees that Bayliss and Marshall <span class="citation">(2022, Ch.3)</span> have constructed provide detailed guidance on the logic of sample assessment. However, these are intended to stimulate reflection and not as sets of rules. Since they are focused on British environments may need to be reconsidered in other regions where the abundance of dateable organic material may vary - limiting choice of materials - and where distinct postdepositional processes may be relevant.</p>
</div>
</div>
<div id="managing-real-world-complications-through-modeling" class="section level3 hasAnchor" number="5.4.7">
<h3><span class="header-section-number">5.4.7</span> Managing real-world complications through modeling<a href="cemetery.html#managing-real-world-complications-through-modeling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Bayesian approaches are rooted in the idea that we should incorporate prior beliefs in assessments of probability. These <em>priors</em> are most obviously operationalized in OxCal as assertions about <a href="cemetery.html#phase_models">sequencing and phases</a>. However, we can incorporate other priors, including for example our beliefs about how our dated events may diverge from our target events. We should do this with our eyes open, though: asserting our beliefs as priors is a claim that we think our beliefs are correct, and that we’re willing to accept that results may be contingent on those beliefs.</p>
<p>To illustrate this Bayesian modeling approach, let’s examine a new set of simulated data, focusing on 12 simulated dates from materials from Burial 11/92 and the question of trying to estimate the date of interment.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-49">Table 5.1: </span>Radiocarbon dates from Burial 11/92
</caption>
<thead>
<tr>
<th style="text-align:left;">
LabID
</th>
<th style="text-align:left;">
burial
</th>
<th style="text-align:left;">
material
</th>
<th style="text-align:right;">
c14age
</th>
<th style="text-align:right;">
c14std
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
LabXX-101
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
gourd
</td>
<td style="text-align:right;">
993
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-102
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
textile
</td>
<td style="text-align:right;">
1056
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-103
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
wood
</td>
<td style="text-align:right;">
1137
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-104
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
human bone
</td>
<td style="text-align:right;">
1046
</td>
<td style="text-align:right;">
34
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-105
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
human bone
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-106
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
human bone
</td>
<td style="text-align:right;">
996
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-107
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
camelid bone
</td>
<td style="text-align:right;">
1027
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-108
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
cane
</td>
<td style="text-align:right;">
1001
</td>
<td style="text-align:right;">
31
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-109
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
cane
</td>
<td style="text-align:right;">
1055
</td>
<td style="text-align:right;">
29
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-110
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
charcoal
</td>
<td style="text-align:right;">
1192
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-111
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
charcoal
</td>
<td style="text-align:right;">
1102
</td>
<td style="text-align:right;">
39
</td>
</tr>
<tr>
<td style="text-align:left;">
LabXX-112
</td>
<td style="text-align:left;">
11/92
</td>
<td style="text-align:left;">
charcoal
</td>
<td style="text-align:right;">
1043
</td>
<td style="text-align:right;">
32
</td>
</tr>
</tbody>
</table>
<p>You can find these data in ‘Bur1192_sim.csv’. Build a bounded phase model in OxCal, and import these as ‘R_Date’ elements. It’s perhaps a bit counter-intuitive to treat this event - the interment of the individual in Burial 11/92 - as a phase in OxCal. However, these dates do meet the chief criterion for a phase: these samples are derived from multiple events - perhaps separated by very little time, but still multiple events - that are part of a coherent distribution. That is, we can think about the radiocarbon dates that we have as samples from a population of dateable events associated with this interment. (One alternative would be to combine these dates; we might pursue that if we are convinced that they come from the same event.) You should wind up with code that looks something like this:</p>
<pre><code>##  // CQL2 generated by stratigraphr v0.3.0.9000
##  Curve(&quot;SHCal20&quot;,&quot;shcal20.14c&quot;);
##  Sequence(&quot;Burial 11/92&quot;)
##  {
##   Boundary(&quot;&quot;);
##   Phase(&quot;11/92&quot;)
##   {
##    R_Date(&quot;LabXX-101&quot;, 993, 30);
##    R_Date(&quot;LabXX-102&quot;, 1056, 37);
##    R_Date(&quot;LabXX-103&quot;, 1137, 35);
##    R_Date(&quot;LabXX-104&quot;, 1046, 34);
##    R_Date(&quot;LabXX-105&quot;, 1030, 32);
##    R_Date(&quot;LabXX-106&quot;, 996, 35);
##    R_Date(&quot;LabXX-107&quot;, 1027, 26);
##    R_Date(&quot;LabXX-108&quot;, 1001, 31);
##    R_Date(&quot;LabXX-109&quot;, 1055, 29);
##    R_Date(&quot;LabXX-110&quot;, 1192, 40);
##    R_Date(&quot;LabXX-111&quot;, 1102, 39);
##    R_Date(&quot;LabXX-112&quot;, 1043, 32);
##   };
##   Boundary(&quot;&quot;);
##  };</code></pre>
<p>With results that look like those in Figure 5.36 (‘View’ –&gt; ‘Plot dates’)… <!-- problem of set.seed() not working here; results discussed below will change --></p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-51"></span>
<img src="imgs/oxcal/sim_example_burial1192.png" alt="Bounded phase model for $^{14}C$ dates from Burial 11/92." width="340" />
<p class="caption">
Figure 5.36: Bounded phase model for <span class="math inline">\(^{14}C\)</span> dates from Burial 11/92.
</p>
</div>
<p>…and an <span class="math inline">\(A_{model}\)</span> of ~57, below the notional threshold of 60 that indicates consistency between model parameters and input data (this will produce an <span style="color: red;">angry red</span> warning).</p>
<p>What causes this low <span class="math inline">\(A_{model}\)</span>? What does it mean that our model parameters are inconsistent with our data? The plot - and the ‘A’ value that can be found in the ‘Table’ view - indicate that one date (LabXX-110) is inconsistent with the others. However, our model structure - the bounded phase - is in effect an assertion that these dates should constitute the kind of sample that we would be likely to draw from a coherent distribution. It is very unlikely that sampling a coherent distribution would result in an assemblage in which most of the dates are similar, but one is dramatically different; this improbability results in the low ‘A’ index.</p>
<div id="chronometric-hygiene" class="section level4 hasAnchor" number="5.4.7.1">
<h4><span class="header-section-number">5.4.7.1</span> Chronometric hygiene<a href="cemetery.html#chronometric-hygiene" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>OxCal’s warning is a feature, not a bug: it is telling us that we would be making a mistake if we were to consider all 12 of the radiocarbon dates from Burial 11/92 to be providing equally useful information about our question (keeping in mind that what we want to know is the date of interment). Identifying one or more samples as inconsistent with the others reminds us that we should be considering the samples themselves closely. We should assess the dates on the samples, weighing how well we think that the <em>dated event</em> matches the <em>target event</em> - and in cases where we suspect a mismatch, <em>we should not simply continue to treat that radiocarbon date as providing reliable age information about the event in question</em>. In this case, we know the target event - the moment of interment - and can consider the dated materials (and their context) to make judgments about the dated event for each sample. This screening process is often termed “chronometric hygiene” <span class="citation">(Spriggs 1989)</span>.</p>
<p>Chronometric hygiene is an issue particularly for <em>legacy dates</em> - that is, radiocarbon dates published over the last ~75 years, which may often provide age estimates for contexts of great interest, but which may have been produced using varying laboratory procedures and often have less associated information than we might like.</p>
</div>
<div id="misfits-offsets-and-outliers" class="section level4 hasAnchor" number="5.4.7.2">
<h4><span class="header-section-number">5.4.7.2</span> Misfits, offsets, and outliers<a href="cemetery.html#misfits-offsets-and-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In cases where we become convinced that a sample is unreliable, we have two options: we can exclude dates from consideration, or we can model an offset. Misfits are dates where the dated event clearly does not match the target event, as determined by other available chronological information (e.g., an Early Holocene date from a context believed to be Late Holocene, or a recent date from a context believed to be &gt;1000 years old). It is these misfits that chronometric hygiene seeks to identify, so that synthetic chronological assessments (<em>e.g.</em>, chronologies of archaeological sites or regions) can be made on the basis of accurate age estimates. Caution has to be exercised in identifying misfits, so that we do not simply reproduce our expectations. For example, it might be reasonable to consider a date from a Lambayeque cemetery (ca. 800 - 1100 CE) a misfit if it were from the middle of the first millennium BCE. However, if that date were from ~700 CE, it <em>might</em> be not be a misfit at all, but instead an indication that the use of Lambayeque material culture and burial customs began earlier than previously believed. Misfits mostly commonly result from the incorporation of already old material into archaeological contexts or from the presence of intrusive material in archaeological contexts. They can also result from inaccurate laboratory analyses, but these instances are relatively rare. Samples of material that is older than its context can sometimes provide useful <em>termini post quem</em>, but intrusive samples are difficult to work with, and are most simply excluded from analysis, along with inaccurate age estimates. Excluded dates should never simply disappear, however - making research transparent and replicable <span class="citation">(Farahani 2024; Nicholson et al. 2023; Marwick 2016)</span> requires that <em>all</em> dates should be presented and the exclusion of any that are not incorporated into further analysis should be justified. This has the additional benefit of facilitating subsequent revision of our own work (we might, for instance, exclude a date and later, revising our assumptions, realize that it was in fact not a misfit).</p>
<p>In practice relatively few dates tend to be <em>obvious</em> misfits. In cases where the difference between dated event and target event is of a known magnitude (or a magnitude that can be reasonably estimated), we can instead include dates in analysis by modeling that <em>offset</em>. Where samples can be identified as incorporating, <em>e.g.</em>, old wood or residence time effects, those effects can be accounted for (as priors) in a model.</p>
<p>The identification of samples that are affected by offsets is generally more difficult than the identification of misfits, since offsets are often of a scale small enough that age estimates will not be obviously inaccurate. Their identification is further complicated by the fact that we must also consider <em>outliers</em>: since we are producing age estimates based on probabilities, we should expect that some samples will not match our expectations. If we are describing a calibrated radiocarbon age using a 95% HDR, there is a 5% chance - 1 in 20 - that the calendar age of the sample is in fact <em>outside</em> of the range we specify. For details of how these cases can be handled in OxCal, see Bronk Ramsey’s <span class="citation">(2009)</span> discussion (confusingly, OxCal uses the same term (“outlier”) to refer to outliers, offsets, and misfits).</p>
<p>In our example case, let’s suppose that we have C/N results from the human bone samples that rule out the possibility of a marine dietary component (admittedly unlikely, near the coast, but we have enough complications already, without adding that one). With that in mind, let’s re-examine Table 5.1 and Figure 5.36. For which samples - based on the materials dated - should we <em>expect</em> a close match between dated event and the moment of burial? For which should we expect offsets, and of what scale?</p>
<p>‘Tools’–&gt;‘Models’–&gt;‘Outlier Model’, and under ‘Prototype’, select “Charcoal”. This will populate the other fields, and when you click ‘Ok’, will add a line to your model that describes a Charcoal Outlier Model, which we can then invoke for any particular sample. To do that, select the sample, then ‘Insert’–&gt;‘Other’–&gt;‘Outlier’, and specify “Charcoal” as the model and “1” as the probability. That will tell the model that we <em>expect</em> the sample to be older than the target event. We’re not sure by how much, but The model that we’ve specified</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-52"></span>
<img src="imgs/oxcal/outlier_model.png" alt="Adding an Outlier Model." width="377" style="float:right; padding:10px" />
<p class="caption">
Figure 5.37: Adding an Outlier Model.
</p>
</div>
<p>You can also of course do this by editing the OxCal code directly, but watch out for <code>{}</code> and <code>;</code>, which are easy to drop, and without which your code will fail.</p>
<p>Applying a charcoal model to all samples for which it’s appropriate and re-running the model will <em>very</em> likely produce a model with a higher ‘A’ index, because we have told the model to <em>expect</em> those samples to be too old, and to adjust the posterior estimates accordingly. Since we don’t know the exact magnitude of the offset, and since it will vary from one sample to the next, the model will calculate which offsets are both consistent with the outlier model that we’ve specified and with other parameters, and adjust the probability density function for each date accordingly. If you plot the results and make sure that “Color outliers’ is selected under ‘Edit’–&gt;‘Format’, you should see results something like Figure 5.38, and an ‘A’ index closer to 120 than to 60.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-53"></span>
<img src="imgs/oxcal/outlier_model.png" alt="Results of applying an Outlier Model." width="377" style="padding:10px" />
<p class="caption">
Figure 5.38: Results of applying an Outlier Model.
</p>
</div>
<p>Here we have enacted modeling as an iterative process - building a model demonstrated that we needed to apply chronometric hygiene (we had implicitly accepted all of our samples as dating the target event), and applying chronometric hygiene enabled us to rebuild and rerun the model. This process - making our assumptions explicit, examining their implications, and reconsidering our assumptions - is an applicaiton of Bayesian modeling that Bayliss <span class="citation">(Bayliss et al. 2007, 4)</span> argues is the operationalization of Hodder’s <span class="citation">(1995)</span> hermeneutic spiral.</p>
<p>If we are confident that our samples date the same event, we can use OxCal’s ‘Combine’ function, which calculates what range of time is consistent with all samples, and tests how likely the samples are to be of the same age (i.e., performs a Ward &amp; Wilson test to determine whether the samples are consistent with our assertion that they have the same radiocarbon content). This provides another means of estimating the date of burial, and because the constraints are stronger (the asserted prior is that samples are of the same age, rather than that they come from a coherent distribution), the estimate is likely to be more precise. That precision depends very directly on our prior belief that these samples date the same event, however; it would be a mistake to accept the results unless we are prepared to defend that asserted prior.</p>
<p>To experiment with ‘Combine’, remove the ‘Sequence’, ‘Phase’, and ‘Boundary’ parameters, and wrap all the samples that you believe to be dating the same event in a ‘Combine’ command. Your code should look something like this, depending on how many dates you include and which you model as outliers (actual dates will vary because they are randomly generated in the simulation process).</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode js"><code class="sourceCode javascript"><span id="cb8-1"><a href="cemetery.html#cb8-1" tabindex="-1"></a> <span class="fu">Plot</span>()</span>
<span id="cb8-2"><a href="cemetery.html#cb8-2" tabindex="-1"></a> {</span>
<span id="cb8-3"><a href="cemetery.html#cb8-3" tabindex="-1"></a>  <span class="fu">Outlier_Model</span>(<span class="st">&quot;Charcoal&quot;</span><span class="op">,</span><span class="fu">Exp</span>(<span class="dv">1</span><span class="op">,-</span><span class="dv">10</span><span class="op">,</span><span class="dv">0</span>)<span class="op">,</span><span class="fu">U</span>(<span class="dv">0</span><span class="op">,</span><span class="dv">3</span>)<span class="op">,</span><span class="st">&quot;t&quot;</span>)<span class="op">;</span></span>
<span id="cb8-4"><a href="cemetery.html#cb8-4" tabindex="-1"></a>  <span class="fu">Curve</span>(<span class="st">&quot;SHCal20&quot;</span><span class="op">,</span><span class="st">&quot;shcal20.14c&quot;</span>)<span class="op">;</span></span>
<span id="cb8-5"><a href="cemetery.html#cb8-5" tabindex="-1"></a>  <span class="fu">Combine</span>(<span class="st">&quot;Burial 11/92&quot;</span>)</span>
<span id="cb8-6"><a href="cemetery.html#cb8-6" tabindex="-1"></a>  {</span>
<span id="cb8-7"><a href="cemetery.html#cb8-7" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-101&quot;</span><span class="op">,</span> <span class="dv">1033</span><span class="op">,</span> <span class="dv">30</span>)<span class="op">;</span></span>
<span id="cb8-8"><a href="cemetery.html#cb8-8" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-102&quot;</span><span class="op">,</span> <span class="dv">1090</span><span class="op">,</span> <span class="dv">37</span>)<span class="op">;</span></span>
<span id="cb8-9"><a href="cemetery.html#cb8-9" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-103&quot;</span><span class="op">,</span> <span class="dv">1130</span><span class="op">,</span> <span class="dv">35</span>)</span>
<span id="cb8-10"><a href="cemetery.html#cb8-10" tabindex="-1"></a>   {</span>
<span id="cb8-11"><a href="cemetery.html#cb8-11" tabindex="-1"></a>    <span class="fu">Outlier</span>(<span class="st">&quot;Charcoal&quot;</span><span class="op">,</span><span class="dv">1</span>)<span class="op">;</span></span>
<span id="cb8-12"><a href="cemetery.html#cb8-12" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb8-13"><a href="cemetery.html#cb8-13" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-104&quot;</span><span class="op">,</span> <span class="dv">990</span><span class="op">,</span> <span class="dv">34</span>)<span class="op">;</span></span>
<span id="cb8-14"><a href="cemetery.html#cb8-14" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-105&quot;</span><span class="op">,</span> <span class="dv">1087</span><span class="op">,</span> <span class="dv">32</span>)<span class="op">;</span></span>
<span id="cb8-15"><a href="cemetery.html#cb8-15" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-106&quot;</span><span class="op">,</span> <span class="dv">1080</span><span class="op">,</span> <span class="dv">35</span>)<span class="op">;</span></span>
<span id="cb8-16"><a href="cemetery.html#cb8-16" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-107&quot;</span><span class="op">,</span> <span class="dv">1075</span><span class="op">,</span> <span class="dv">26</span>)<span class="op">;</span></span>
<span id="cb8-17"><a href="cemetery.html#cb8-17" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-108&quot;</span><span class="op">,</span> <span class="dv">1049</span><span class="op">,</span> <span class="dv">31</span>)<span class="op">;</span></span>
<span id="cb8-18"><a href="cemetery.html#cb8-18" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-109&quot;</span><span class="op">,</span> <span class="dv">1081</span><span class="op">,</span> <span class="dv">29</span>)<span class="op">;</span></span>
<span id="cb8-19"><a href="cemetery.html#cb8-19" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-110&quot;</span><span class="op">,</span> <span class="dv">1277</span><span class="op">,</span> <span class="dv">40</span>)</span>
<span id="cb8-20"><a href="cemetery.html#cb8-20" tabindex="-1"></a>   {</span>
<span id="cb8-21"><a href="cemetery.html#cb8-21" tabindex="-1"></a>    <span class="fu">Outlier</span>(<span class="st">&quot;Charcoal&quot;</span><span class="op">,</span><span class="dv">1</span>)<span class="op">;</span></span>
<span id="cb8-22"><a href="cemetery.html#cb8-22" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb8-23"><a href="cemetery.html#cb8-23" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-111&quot;</span><span class="op">,</span> <span class="dv">1104</span><span class="op">,</span> <span class="dv">39</span>)</span>
<span id="cb8-24"><a href="cemetery.html#cb8-24" tabindex="-1"></a>   {</span>
<span id="cb8-25"><a href="cemetery.html#cb8-25" tabindex="-1"></a>    <span class="fu">Outlier</span>(<span class="st">&quot;Charcoal&quot;</span><span class="op">,</span><span class="dv">1</span>)<span class="op">;</span></span>
<span id="cb8-26"><a href="cemetery.html#cb8-26" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb8-27"><a href="cemetery.html#cb8-27" tabindex="-1"></a>   <span class="fu">R_Date</span>(<span class="st">&quot;LabXX-112&quot;</span><span class="op">,</span> <span class="dv">1147</span><span class="op">,</span> <span class="dv">32</span>)</span>
<span id="cb8-28"><a href="cemetery.html#cb8-28" tabindex="-1"></a>   {</span>
<span id="cb8-29"><a href="cemetery.html#cb8-29" tabindex="-1"></a>    <span class="fu">Outlier</span>(<span class="st">&quot;Charcoal&quot;</span><span class="op">,</span><span class="dv">1</span>)<span class="op">;</span></span>
<span id="cb8-30"><a href="cemetery.html#cb8-30" tabindex="-1"></a>   }<span class="op">;</span></span>
<span id="cb8-31"><a href="cemetery.html#cb8-31" tabindex="-1"></a>  }<span class="op">;</span></span>
<span id="cb8-32"><a href="cemetery.html#cb8-32" tabindex="-1"></a> }<span class="op">;</span></span></code></pre></div>
<script>
 Plot()
 {
  Outlier_Model("Charcoal",Exp(1,-10,0),U(0,3),"t");
  Curve("SHCal20","shcal20.14c");
  Combine("Burial 11/92")
  {
   R_Date("LabXX-101", 1033, 30);
   R_Date("LabXX-102", 1090, 37);
   R_Date("LabXX-103", 1130, 35)
   {
    Outlier("Charcoal",1);
   };
   R_Date("LabXX-104", 990, 34);
   R_Date("LabXX-105", 1087, 32);
   R_Date("LabXX-106", 1080, 35);
   R_Date("LabXX-107", 1075, 26);
   R_Date("LabXX-108", 1049, 31);
   R_Date("LabXX-109", 1081, 29);
   R_Date("LabXX-110", 1277, 40)
   {
    Outlier("Charcoal",1);
   };
   R_Date("LabXX-111", 1104, 39)
   {
    Outlier("Charcoal",1);
   };
   R_Date("LabXX-112", 1147, 32)
   {
    Outlier("Charcoal",1);
   };
  };
 };

</script>
</div>
<div id="what-bayesian-modeling-can-and-cant-do" class="section level4 hasAnchor" number="5.4.7.3">
<h4><span class="header-section-number">5.4.7.3</span> What Bayesian modeling can (and can’t) do<a href="cemetery.html#what-bayesian-modeling-can-and-cant-do" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The decision about whether ‘Combine’ is justifiable or not, and for which dates, is representative of Bayesian modeling more generally. Asserting a prior belief that these samples date the same event and should be modeled with ‘Combine’ is an <em>argument</em>. Similarly, there is no magic bullet for identifying and treating outliers, misfits, and offsets. Rather, we have to make <em>arguments</em> about which samples are most likely to match age of target event. The fact that we are able to do so is an expression of the underlying logic of Bayesian approaches: we know more about the samples than just their measured radiocarbon ages (for instance, we are likely to know what materials were dated, what context they came from, and how those materials and contexts relate to other materials and contexts), and and we incorporate that knowledge into our age estimates. Bayesian modeling is basically a tool for formalizing that process.</p>
<p>The potential of Bayesian modeling to produce more precise age estimates from radiocarbon dates (and other chronological data) has rightly been a source of excitement in archaeology. Applications of Bayesian modeling of archaeological radiocarbon data have made it possible to describe time in the past with higher resolution, enabling interpretation of the human past that more closely approximates human experience <span class="citation">(Whittle and Bayliss 2007)</span>, as well as to more robustly link archaeological events to paleoclimate data <span class="citation">(Manning et al. 2020)</span>. These are not just practical advances, but have theoretical implications for the kinds of interpretations that we can make about the human past <span class="citation">(Bayliss and Whittle 2018b; Griffiths et al. 2023; Griffiths 2017)</span>.</p>
<p>A more immediate advantage is that Bayesian modeling forces us to explicitly articulate our assumptions. It also highlights the importance of clear questions, clearly and thoroughly understood samples, and explicit articulation/consideration/justification of prior beliefs. The latter emphasizes a conceptual key to interpretation of model results: model consistency (measured with OxCal’s agreement [‘A’] index) is most useful as a tool for confronting prior beliefs with data, and/or for exploring how consistent data are. Model consistency can also be a useful indicator of inconsistencies between priors, but consistencies among priors cannot indicate anything beyond coherence.</p>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="radiocarbon-in-central-andean-archaeology.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exercise-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": false,
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
